### ISSUE TITLE
Cinnamon: Tray tooltips don't interpret pango markups

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/mint21-beta#1]
Issue: Notes version 1.10 shows <i>Left click to toggle notes</i> <i>Middle click to toggle the manager</i>
See the screen shots from version 1.08 and 1.10 as comparison.
Issue is present in the Cinnamon and Xfce desktops but not in MATE.

Expected behavior:
Version 1.10 tooltip should be clear of the markup as version 1.08.

How to reproduce:
Launch Sticky Notes and hover the mouse over the Notes tray icon.

![notes-ver-1-8](https://user-images.githubusercontent.com/45599505/179006304-d3e84372-b5d9-4119-beee-fe777f543a01.png)
![notes-ver-1-10](https://user-images.githubusercontent.com/45599505/179006326-3d5eaf78-60c2-4333-b243-a0aa903e8075.png)

**Comment by mahtiankka** [comment]
I have the same problem too.

**Comment by clefebvre** [comment]
I think this is fixed in Cinnamon git master.

**Comment by Acheron17** [comment]
Fix was confirmed.
