### ISSUE TITLE
[Cinnamon] Grouped window list/Thumbnails/Hover Peek is not working

### ISSUE THREAD

**Issue by spamegg1** [linuxmint/mint21-beta#10]
As the title says. Here is a video
[cinnamon-2022-07-14:19:01:45.webm](https://user-images.githubusercontent.com/4255997/179026734-7e851743-4855-4070-9da0-71f86e39aaf8.webm)

Let me know if more info is needed.

**Comment by spamegg1** [comment]
Thanks.

**Comment by spamegg1** [comment]
After the updates today (Cinnamon 5.4.3 and all the other updates) the issue is still present.

**Comment by spamegg1** [comment]
The issue is still present with the Cinnamon 5.4.5 update (July 20).

**Comment by JosephMcc** [comment]
It's working as expected here.

**Comment by spamegg1** [comment]
If I disable "Show Thumbnails" then it works.
If I enable "Show Thumbnails" then it works inconsistently.
Here is a video:
[cinnamon-2022-07-21T080613+0300.webm](https://user-images.githubusercontent.com/4255997/180134073-62ce7a45-e139-4cc2-8e1f-ed6f56b8ac0b.webm)

**Comment by JosephMcc** [comment]
Ok. So the best I can tell here, it seems that sometimes we are missing the event when the mouse enters the thumbnail. Testing this myself, If I move the cursor slower, it always works. I'm not actually sure if that's a new bug or was this way in older Cinnamon versions.

**Comment by spamegg1** [comment]
I can confirm that "entering the thumbnail with the cursor slowly" indeed works. (Although it has to be quite slow for it to be consistent.) And entering it fast still works, but rarely.

It was definitely not like that on Mint 20.3. I could enter the thumbnail as fast as I want and it would always work. So much so that I've built muscle memory for it.

Thanks for looking into it Joseph.

**Comment by spamegg1** [comment]
The same "slow/fast" issue also seems to be present in auto-hiding the Panel. If I move the cursor too quickly, the hidden panel is revealed but does not hide back. Here is a video:
[cinnamon-2022-07-22T141203+0300.webm](https://user-images.githubusercontent.com/4255997/180427719-bd268463-46b5-4e8d-9893-b5bd617f60c2.webm)
