### ISSUE TITLE
[Xfce] (Live session ONLY) Error when trying to download & install Nemo from 'Software Manager'

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21-beta#101]
(tested on both live Xfce and a local fully-updated installation of Xfce as of 2022-07-15, but this issue _only_ occurs with a live session)

**Describe the bug**
Simply put, if you try to download & install Nemo from 'Software Manager' on a live session of Xfce, it will fail and throw up the following error:

```
Failed to fetch http://packages.linuxmint.com/pool/backport/n/nemo/libnemo-extension1_5.4.0%%2bvanessa_amd64.deb 404  Not Found [IP: 68.235.39.11 80]
Failed to fetch http://packages.linuxmint.com/pool/backport/n/nemo/nemo-data_5.4.0%%2bvanessa_all.deb 404  Not Found [IP: 68.235.39.11 80]
Failed to fetch http://packages.linuxmint.com/pool/backport/n/nemo/nemo_5.4.0%%2bvanessa_amd64.deb 404  Not Found [IP: 68.235.39.11 80]
Failed to fetch http://packages.linuxmint.com/pool/backport/n/nemo-fileroller/nemo-fileroller_5.4.0%%2bvanessa_amd64.deb 404  Not Found [IP: 68.235.39.11 80]
```

**To Reproduce**
1. boot the live ISO for Xfce
2. open the 'Software Manager'
3. search for `nemo`
4. install Nemo
5. observe how, half way through, it'll throw up the aforementioned error

**Expected behavior**
Nemo should install successfully without an error occurring.

**Screenshots**
![nemo on live xfce](https://user-images.githubusercontent.com/11896003/179440552-53aa6123-6f11-48c3-8182-50452987ea7a.png)

**Comment by mtwebster** [comment]
This is likely because nemo 5.4.1 had already been released, meaning 5.4.0 no longer existed. Updating the apt cache would fix this.

In the final release, this should not be the case, as we won't be frequently updating like we're doing currently.
