### ISSUE TITLE
(intentional?) Nemo - right-click dragging a file from a Nemo window to a different location straight-up doesn't work (context menu always just instantly appears)

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21-beta#103]
(tested on both a live session of Cinnamon as well as fully-updated local installations of both Cinnamon and Xfce as of 2022-07-15; could not test on a live session of Xfce due to issue #101)

**Describe the bug**
Simply put, if you try to right-click drag any file from one Nemo window to any other location, the context menu will always just instantly appear and no drang-and-drop action will occur.

**To Reproduce**
1. boot a copy of Mint 21 Cinnamon (whether a live session of a local installation) or Xfce (local installation only due to issue #101)
2. open Nemo (on Xfce this requires you to first install Nemo of course)
3. create a new blank file or folder (presumably in your /home/[user] directory)
4. open another instance of Nemo and navigate to /home/Downloads
5. right-click and hold on that file that you created in step 5 and try to drag it into the window you opened in step 4
6. observed how the context menu instantly appeared the moment you right-clicked and no drag-and-drop action occured

**Expected behavior**
How it works in Thunar (at least on Xfce) - doing step 5 on Xfce from one Thunar window to another Thunar window instead results in the file being dragged and a small context menu appearing when you let go of right-click with options for "Move here", "Copy here", and "Link here"

**Additional context**
My impression was that Nemo was all-around more feature-filled than Thunar yet I'm actually kind of surprised that this one action is not present in Nemo?

As mentioned in the title, this may actually be intentional behavior for all I know.

**Comment by mtwebster** [comment]
Thunar is an aberration in this case. Nemo works the same way as any other program I've ever used. I think having it behave differently - such as having a delay, or even allowing it to initiate a drag - would be very frustrating for people.

Having it open immediately on button press allows people to quickly select an item on button release. Personally the short delay they have there would drive me crazy. You can get the various copy/move options using modifier keys while dragging (ctrl-shift gives you the popup menu when you drop the item).

**Comment by NintendoManiac64** [comment]
> Having it open immediately on button press allows people to quickly select an item on button release.

Isn't having the menu appear on button release just as quick?  This is the way I use it in Thunar to instantly access the context menu while still allowing for the right-click drag operation.

> the short delay they have there would drive me crazy

I don't use the short delay since that method takes longer than just clicking twice or even clicking once then pressing the according keyboard key to quickly select a specific context menu option.

...that being said, on the subject of short delays driving a person crazy, the short delay that Nemo has when loading any folder (particularly in "List View") is actually a big reason I prefer Thunar because that delay prevents me and/or interrupts the flow from just quickly clicking from one folder to another to another to another within one or two seconds.  So I find it peculiar that any such short delay is something that would drive you crazy when, in my view, Nemo as a whole doesn't even seem to be focused on performance/latency/speed/etc.
