### ISSUE TITLE
cinnamon: systray icon show up at coordinates 0,0

### ISSUE THREAD

**Issue by MichelHanzen** [linuxmint/mint21-beta#105]
**Describe the bug**
MinimWatch Applet - Problem with icon

**To Reproduce**
After the installation according to https://minimserver.com/install-linux-mwatch.html, the application behaves correctly but the icon appeared black in the applet panel. The content of the icon (gray/yellow/green depending of the status aof the minimserver) appears in the upper left corner of the desktop.

**Expected behavior**
Icon content should appear un the applet panel.

**Screenshots**
![Capture d’écran du 2022-07-18 16-18-12](https://user-images.githubusercontent.com/29270535/179531999-b6d1ce3e-75ce-4ca6-8e20-81509829744e.png)
![Capture d’écran du 2022-07-18 16-20-57](https://user-images.githubusercontent.com/29270535/179532377-eec44f69-bfcd-459c-84bb-6a35604014b7.png)
@

**Hardware and mintUpdate**
[system info.odt](https://github.com/linuxmint/mint21-beta/files/9132683/system.info.odt)
Last update on 18/07/2022 installed

**Additional context**
Linux Mint 21 Cinnamon

**Comment by mtwebster** [comment]
This is an issue with the systray applet, and happens with other java programs:
confirmed with JDownloader2: https://github.com/linuxmint/cinnamon/issues/10830#issuecomment-1176342326

**Comment by clefebvre** [comment]
is it specific to Java apps using gtk.statusicon?

**Comment by mtwebster** [comment]
Not sure if it's all Java apps (I don't know the library/toolkit situation for Java) but this issue is not specific to Cinnamon and has been around a while:
https://bugzilla.redhat.com/show_bug.cgi?id=1014448
https://github.com/MartinPL/Tray-Icons-Reloaded/issues/20

There are numerous other reports of other issues, similar and not.

**Comment by clefebvre** [comment]
Could be an issue between Java and Gtk by the look of things.. if it's going through socket/plug and using xembed there's nothing we can do at DE/Xapp level.

Java devs might need to use a different tray API. I don't know what's available to them though. If they can tap into GI, then xapp.statusicon should work better.

**Comment by mtwebster** [comment]
It used to 'sort of' work in 5.2 in Cinnamon (the icon was in the right place, but with the same background, but due to changes in muffin these icons are handled differently now.
