### ISSUE TITLE
[RFE] Advice for Driverless Printing and Scanning

### ISSUE THREAD

**Issue by debiantriage** [linuxmint/mint21-beta#107]
This advice [concerning printing and scanning](https://www.linuxmint.com/rel_vanessa_cinnamon_whatsnew.php) is offered for Linux Mint 21 Cinnamon:

> If your printer/scanner doesn't work properly disable printerless printing/scanning by removing the ipp-usb and airscan packages. Then install drivers from your manufacturer.

- One of the best changes Mint made after 20.0 was to remove **ippusbxd** from the archives and provide **ipp-usb** and **sane-airscan**. This allowed efficient, effective, targeted and successful support for users with **modern** MFPs in the [Printers & Scanners forum](https://forums.linuxmint.com/viewforum.php?f=51).

- To the best of my knowledge, users following the advice given have benefited from installing these two packages and there has not been a single case of their *not working properly*. Many (if not most) of the [devices that work with sane-airscan](https://github.com/alexpevzner/sane-airscan) are the result of testing by Mint users.
- In the worlds of Debian and Ubuntu most issues raised have been identified as **device firmware** issues and, on the whole, attended to. In other words, ipp-usb and sane-airscan themselves are sound.
- Promoting vendor drivers as a solution is a retrograde step, certainly as far as printing is concerned; in 2/3 years CUPS will not support them. ipp-usb will remain crucial for USB printing.
- Issues with ipp-usb and sane-airscan are best submitted to the  Printers & Scanners forum or upstream rather than tackled by vendor drivers. This benefits everyone now and in the future.

I hope that at least the first three points above would lead to a change in the wording on the New Features page.

-- 
brian_p

**Comment by clefebvre** [comment]
The doc isn't up to date for 21 and needs to be edited. This is tracked by https://github.com/linuxmint/mint21-beta/issues/109
