### ISSUE TITLE
[Cinnamon - Live Installer] mintsources: "Failed to download repository information (cdrom)"

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/mint21-beta#112]
**Describe the bug**
On a live session, in Software Sources, i select some local mirror, update the cache, wait, and get an error message.

**To Reproduce**
1. Start a live session
1. Go to Menu > Administration > Software Sources
1. Click on one of the two drop-down lists to select a local mirror
1. When prompted, click OK to update your APT cache
1. See error message: `E:The repository 'cdrom://Linux Mint 21 _Vanessa_ - Release amd64 20220711 jammy Release' does not have a Release file.`

**Expected behavior**
On this first introduction to LinuxMint, before installing, i would appreciate not having to face strange error messages on my first basic steps.

**Screenshots**
![VirtualBox_LinuxMint-21-Cinnamon-BETA-live-failed-repo-info](https://user-images.githubusercontent.com/31940713/179600171-2235558f-9ff6-4c17-92dd-3fb8781b94ab.png)

**Additional context**
This is a very old bug. Already reported on https://github.com/linuxmint/mint20.3-beta/issues/42 It never got fixed.

> Postponed towards Mint 21. We're likely to work on ubiquity and the APT backends for the next release.

—clefebvre (quoted from https://github.com/linuxmint/mint20.3-beta/issues/42#issuecomment-1004064176)

**Comment by clefebvre** [comment]
This is already in the roadmap. It was looked at in 21 but we didn't fix it. It's a cosmetic issue.

**Comment by SebastJava** [comment]
I'm sure there are people who are skeptical, fearful, but want to try LinuxMint for the first time. When they see this message, many will see it as the confirmation of their fears and will venture no further.

This error message appears often and in several ways. It suffices, for example, to click on "Refresh" in mintUpdate.

This "cosmetic" issue was an essential one, IMHO.
