### ISSUE TITLE
[Xfce] Desktop only - when multiple files are highlighted, "Properties" is greyed out in the right-click context menu

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21-beta#113]
(tested in a live session of Xfce as well as a fully-updated local installation as of 2022-07-15)

**Describe the bug**
When you have multiple files highlighted on the desktop, if you then open the right-click context menu for those highlighted files, you will see that "Properties" is greyed out.

**To Reproduce**
1. boot into Mint 21 beta Xfce (whether a local installation or a live session)
2. have multiple files located on the desktop (you can create them yourself or copy/move them from elsewhere)
3. highlight multiple files on your desktop
4. right-click on one of those highlighted files
5. notice how "Properties" is greyed out

**Expected behavior**
"Properties" should not be greyed out considering that "Properties" works for multiple files in Thunar as well as the Cinnamon desktop as well as in Nemo.

**Screenshots**
![desktop](https://user-images.githubusercontent.com/11896003/179603301-6592280d-f81c-44cf-a3dd-f917372c987c.png)

**Comment by clefebvre** [comment]
This is upstream at https://gitlab.xfce.org/xfce/xfdesktop/-/issues/112.
