### ISSUE TITLE
Nemo & Thunar (list view ONLY) - in a folder with files with no files highlighted, pressing the 'Home' key does not highlight the top-listed file

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21-beta#114]
(tested with basically every combination of Nemo, Thunar, Cinnamon, Xfce, live session, local OS installations, etc that you can think of)

**Describe the bug**
On both Nemo and Thunar regardless of whether its Cinnamon or Xfce, if you have your folder view set to "List View" and you view a folder that has multiple files and no files are highlighted, pressing the "Home" key does not highlight the top-listed file.

**To Reproduce**
1. boot Mint 21 beta, whether Cinnamon or Xfce, of some variety
2. open Nemo or Thunar
3. make sure your folder view is set to "List View" and that it's also using that by default
4. navigate to a folder with multiple files, such as `/etc/`
5. press the "Home" key on your keyboard
6. notice how no files become highlighted

**Expected behavior**
Step 6 in the above example should have highlighted the top-listed file as this is what occurs if, in step 3, you had instead set Nemo/Thunar to "Compact View" or "Icon View".

**Comment by clefebvre** [comment]
Confirmed. This should be a feature request on nemo (github.com/linuxmint/nemo) and thunar (in the xfce gitlab), not a bug report for this BETA.

**Comment by NintendoManiac64** [comment]
Is this really considered a feature request rather than a bug when both the 'Home' key and 'End' key work when a file was highlighted in list view yet, when no files are highlighted, the 'End' key still works while the 'Home' key does not work.

Regardless, as a sanity check, I tested it in Thunar 4.6.11 in Manjaro Xfce 21.3.5 and the issue is still there so, at least for Thunar, it's clearly not a Mint/Ubuntu/Debian-related issue.
