### ISSUE TITLE
[Cinnamon] 

### ISSUE THREAD

**Issue by Unavailium** [linuxmint/mint21-beta#115]
**Describe the bug**
Desktop Cube extension not working in Mint21 Beta

**To Reproduce**
Go to System Settings, 
Download and install Desktop Cube
Click + to enable the cube
Press Ctrl-Alt-RightArrow to switch desktops. 
Observe that nothing happens (the sliding desktop switch no longer happens)

Disabling the Desktop Cube restores the sliding desktop switching function.

**Expected behavior**
I expect Ctrl-Alt-RightArrow and Ctrl-Alt-LeftArrow to switch desktops with a rotating cube effect.

**Screenshots**
N/A

**Hardware and mintUpdate**
Probably not relevant, but using nVidia drivers:
--------------------------------------------------
System:
  Kernel: 5.15.0-41-generic x86_64 bits: 64 compiler: gcc v: 11.2.0
    Desktop: Cinnamon 5.4.4 tk: GTK 3.24.33 vt: 7 dm: LightDM 1.30.0
    Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop System: Micro-Star product: MS-7A38 v: 8.0
    serial: <superuser required>
  Mobo: Micro-Star model: B450M PRO-VDH MAX (MS-7A38) v: 8.0
    serial: <superuser required> UEFI: American Megatrends v: B.40
    date: 11/07/2019
Battery:
  Device-1: hidpp_battery_0 model: Logitech Wireless Mouse MX Master
    serial: <filter> charge: 55% (should be ignored) rechargeable: yes
    status: Discharging
  Device-2: hidpp_battery_1
    model: Logitech Wireless Illuminated Keyboard K800 serial: <filter>
    charge: 55% (should be ignored) rechargeable: yes status: Discharging
CPU:
  Info: 6-core model: AMD Ryzen 5 3600 bits: 64 type: MT MCP smt: enabled
    arch: Zen 2 rev: 0 cache: L1: 384 KiB L2: 3 MiB L3: 32 MiB
  Speed (MHz): avg: 2724 high: 3603 min/max: 2200/4208 boost: enabled
    cores: 1: 3602 2: 2398 3: 2056 4: 3603 5: 2057 6: 2057 7: 3594 8: 2055
    9: 2054 10: 3599 11: 3600 12: 2013 bogomips: 86395
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: NVIDIA TU116 [GeForce GTX 1660 SUPER] vendor: ASUSTeK
    driver: nvidia v: 515.48.07 pcie: speed: 2.5 GT/s lanes: 16 ports:
    active: none off: HDMI-A-1 empty: DP-1,DVI-D-1 bus-ID: 29:00.0
    chip-ID: 10de:21c4 class-ID: 0300
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: nvidia
    unloaded: fbdev,modesetting,nouveau,vesa gpu: nvidia display-ID: :0
    screens: 1
  Screen-1: 0 s-res: 1920x1200 s-dpi: 93 s-size: 524x321mm (20.6x12.6")
    s-diag: 615mm (24.2")
  Monitor-1: HDMI-0 res: 1920x1200 hz: 60 dpi: 94
    size: 518x324mm (20.4x12.8") diag: 611mm (24.1")
  OpenGL: renderer: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2
    v: 4.6.0 NVIDIA 515.48.07 direct render: Yes
Audio:
  Device-1: NVIDIA TU116 High Definition Audio vendor: ASUSTeK
    driver: snd_hda_intel v: kernel pcie: speed: 8 GT/s lanes: 16
    bus-ID: 29:00.1 chip-ID: 10de:1aeb class-ID: 0403
  Device-2: AMD Starship/Matisse HD Audio vendor: Micro-Star MSI
    driver: snd_hda_intel v: kernel pcie: speed: 16 GT/s lanes: 16
    bus-ID: 2b:00.4 chip-ID: 1022:1487 class-ID: 0403
  Sound Server-1: ALSA v: k5.15.0-41-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet
    vendor: Micro-Star MSI driver: r8169 v: kernel pcie: speed: 2.5 GT/s
    lanes: 1 port: f000 bus-ID: 25:00.0 chip-ID: 10ec:8168 class-ID: 0200
  IF: eth0 state: up speed: 1000 Mbps duplex: full mac: <filter>
  IF-ID-1: wg0 state: unknown speed: N/A duplex: N/A mac: N/A
  IF-ID-2: wgvpn state: unknown speed: N/A duplex: N/A mac: N/A
Drives:
  Local Storage: total: 2.84 TiB used: 338.77 GiB (11.7%)
  ID-1: /dev/sda vendor: Kingston model: SA400S37120G size: 111.79 GiB
    speed: 6.0 Gb/s type: SSD serial: <filter> rev: 71E0 scheme: GPT
  ID-2: /dev/sdb vendor: Western Digital model: WD10EZEX-00WN4A0
    size: 931.51 GiB speed: 6.0 Gb/s type: HDD rpm: 7200 serial: <filter>
    rev: 1A01 scheme: MBR
  ID-3: /dev/sdc vendor: Western Digital model: WD20EZRZ-00Z5HB0
    size: 1.82 TiB speed: 6.0 Gb/s type: HDD rpm: 5400 serial: <filter>
    rev: 0A80 scheme: GPT
Partition:
  ID-1: / size: 38.15 GiB used: 13.37 GiB (35.1%) fs: ext4 dev: /dev/sda2
  ID-2: /boot/efi size: 476 MiB used: 5.2 MiB (1.1%) fs: vfat
    dev: /dev/sda1
  ID-3: /home size: 877.37 GiB used: 325.39 GiB (37.1%) fs: ext4
    dev: /dev/sdb6
Swap:
  ID-1: swap-1 type: partition size: 9.77 GiB used: 0 KiB (0.0%) priority: -2
    dev: /dev/sdb5
Sensors:
  System Temperatures: cpu: N/A mobo: N/A gpu: nvidia temp: 43 C
  Fan Speeds (RPM): N/A gpu: nvidia fan: 35%
Repos:
  Packages: apt: 2850
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/brave-browser-release.list
    1: deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http://packages.linuxmint.com vanessa main upstream import backport
    2: deb http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
    3: deb http://archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http://security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
Info:
  Processes: 285 Uptime: 2h 11m wakeups: 14 Memory: 31.3 GiB
  used: 1.36 GiB (4.4%) Init: systemd v: 249 runlevel: 5 Compilers:
  gcc: 11.2.0 alt: 11 Shell: Bash v: 5.1.16 running-in: gnome-terminal
  inxi: 3.3.13

--------------------------------------------------
**Additional context**
None I can think of

**Comment by leigh123linux** [comment]
Report your issue against DesktopCube@yare

https://github.com/linuxmint/cinnamon-spices-extensions/issues
