### ISSUE TITLE
[Xfce] If 'Bulk Rename' is minimized, then it'll automatically restore itself any time you open Thunar or un-minimize an already-open Thunar window

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21-beta#116]
(tested in a live session of Xfce as well as a fully-updated local installation as of 2022-07-15, though it may technically occur on Cinnamon as well if you install the corresponding software)

**Describe the bug**
Simply put, if 'Bulk Rename' is minimized then, any time that you open Thunar or un-minimized an already-open Thunar window, 'Bulk Rename' will also end up being automatically un-minimized.

**To Reproduce**
1. boot into Mint 21 beta Xfce (whether a local installation or a live session)
2. open 'Bulk Rename'
3. minimized the program window for 'Bulk Rename'
4. open Thunar
5. observe has 'Bulk Rename' unminimized itself
6. minimize 'Bulk Rename'
7. minimize Thunar
8. un-minimize Thunar
9. observe has 'Bulk Rename' also un-minimized itself

**Expected behavior**
'Bulk Rename' should not un-minimize itself when opening a new instance of Thunar or when un-minimizing and already-open Thunar window.

**Additional context**
To clarify, I am not talking about 'Bulky' but rather the 'Bulk Rename' that comes bundled with Mint Xfce.

**Comment by mtwebster** [comment]
This is normal - they are part of the same process and I'm pretty sure this is deliberate behavior.

- If you launch the bulk renamer on its own (which is a reasonable thing to do if you just want to add files manually, it has a minimize button in the titlebar.
- If you open thunar  and select multiple files, then press F2 (or rename from the context menu), you'll notice the rename window does *not* have a minimize button.

They're still the same dialog, but I think their expectation is that if you want the bulk rename window while a normal thunar window is open, you've probably activated it from a thunar action, not from the menu, so there's no reason to be able to minimize it except as one with the parent window.

Obviously it's possible you opened the rename window from the menu initially, then launched a thunar window after - in the case you describe - maybe their mutual visiblity should be disconnected in this instance, but that's an issue to take up with the Thunar developers.
