### ISSUE TITLE
[Cinnamon] Microphone sound level does not move

### ISSUE THREAD

**Issue by mahtiankka** [linuxmint/mint21-beta#117]
The line representing the volume of the microphone does not move. The microphone works normally. Tested on two machines, with external and internal microphones.
![Mic_level](https://user-images.githubusercontent.com/48694735/179684161-af077d0c-46be-472d-ab34-bef4fd92cba0.jpg)

**Comment by Acheron17** [comment]
This seems like a duplicate of
https://github.com/linuxmint/mint21-beta/issues/7

**Comment by mtwebster** [comment]
Duplicate of #7
