### ISSUE TITLE
[Cinnamon] elisa crashes on startup

### ISSUE THREAD

**Issue by RTinIB** [linuxmint/mint21-beta#119]
elisa version 21.12.3-ubuntu1 crashes on startup

**To Reproduce**
1. install elisa using sudo apt install elisa
2. In terminal type elisa
3. Error shown below

**Expected behavior**
elisa should start normally

**Screenshots**
bob@wolfvmmcb:~$ sudo apt install elisa
[sudo] password for bob:       
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  elisa
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/1,913 kB of archives.
After this operation, 4,154 kB of additional disk space will be used.
Selecting previously unselected package elisa.
(Reading database ... 341404 files and directories currently installed.)
Preparing to unpack .../elisa_21.12.3-0ubuntu1_amd64.deb ...
Unpacking elisa (21.12.3-0ubuntu1) ...
Setting up elisa (21.12.3-0ubuntu1) ...
Processing triggers for desktop-file-utils (0.26+mint1+vanessa) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu3) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
bob@wolfvmmcb:~$ elisa
kf.kirigami: Warning: Theme implementations should use Kirigami.BasicThemeDefinition for its root item
kf.kirigami: Failed to find a Kirigami platform plugin
qrc:/qml/ElisaMainWindow.qml:19:1: QML ElisaMainWindow: Accessible must be attached to an Item
file:///usr/lib/x86_64-linux-gnu/qt5/qml/org/kde/kirigami.2/Page.qml:348: Error: Cannot assign QObject* to PageRow_QMLTYPE_90*
file:///usr/lib/x86_64-linux-gnu/qt5/qml/org/kde/kirigami.2/Page.qml:348: Error: Cannot assign QObject* to PageRow_QMLTYPE_90*
kf.kirigami: Units.devicePixelRatio is deprecated (since 5.86): This returns 1 when using Qt HiDPI scaling.
file:///usr/lib/x86_64-linux-gnu/qt5/qml/org/kde/kirigami.2/PageRow.qml:674:5: QML Shortcut: Shortcut: Only binding to one of multiple key bindings associated with 14. Use 'sequences: [ <key> ]' to bind to all of them.
file:///usr/lib/x86_64-linux-gnu/qt5/qml/org/kde/kirigami.2/PageRow.qml:670:5: QML Shortcut: Shortcut: Only binding to one of multiple key bindings associated with 13. Use 'sequences: [ <key> ]' to bind to all of them.
Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations.
Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations.
org.kde.elisa.indexers.manager: Local file system indexer is inactive
org.kde.elisa.indexers.manager: Baloo indexer is unavailable
org.kde.elisa.indexers.manager: Baloo indexer is inactive
org.kde.elisa.database: begin update to v9 of database schema
org.kde.elisa.database: finished update to v9 of database schema
org.kde.elisa.database: begin update to v11 of database schema
Segmentation fault (core dumped)

**Hardware and mintUpdate**
Mint 21 running in virtual machine:
System:
  Kernel: 5.15.0-41-generic x86_64 bits: 64 compiler: gcc v: 11.2.0
    Console: pty pts/1 DM: LightDM 1.30.0 Distro: Linux Mint 21 Vanessa
    base: Ubuntu 22.04 jammy
Machine:
  Type: Kvm System: QEMU product: Standard PC (i440FX + PIIX, 1996)
    v: pc-i440fx-focal serial: N/A Chassis: type: 1 v: pc-i440fx-focal
    serial: N/A
  Mobo: N/A model: N/A serial: N/A BIOS: SeaBIOS v: 1.13.0-1ubuntu1.1
    date: 04/01/2014
CPU:
  Info: 2x 1-core model: Intel Xeon E312xx (Sandy Bridge IBRS update)
    bits: 64 type: SMP smt: <unsupported> arch: Sandy Bridge rev: 1 cache:
    L1: 2x 64 KiB (128 KiB) L2: 2x 4 MiB (8 MiB) L3: 2x 16 MiB (32 MiB)
  Speed (MHz): avg: 3093 min/max: N/A cores: 1: 3093 2: 3093
    bogomips: 12371
  Flags: avx lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Red Hat Virtio GPU driver: virtio-pci v: 1 bus-ID: 00:02.0
    chip-ID: 1af4:1050 class-ID: 0300
  Display: server: X.Org v: 1.21.1.3 driver: X: loaded: modesetting
    unloaded: fbdev,vesa gpu: virtio_gpu display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1600x900 s-dpi: 96 s-size: 423x238mm (16.7x9.4")
    s-diag: 485mm (19.1")
  Monitor-1: Virtual-1 res: 1600x900 hz: 60 size: N/A modes: max: 1024x768
    min: 640x480
  OpenGL: renderer: llvmpipe (LLVM 13.0.1 256 bits) v: 4.5 Mesa 22.0.1
    direct render: Yes
Audio:
  Device-1: Intel 82801I HD Audio vendor: Red Hat QEMU Virtual Machine
    driver: snd_hda_intel v: kernel bus-ID: 00:06.0 chip-ID: 8086:293e
    class-ID: 0403
  Sound Server-1: ALSA v: k5.15.0-41-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel 82371AB/EB/MB PIIX4 ACPI
    vendor: Red Hat Qemu virtual machine type: network bridge
    driver: piix4_smbus v: N/A port: N/A bus-ID: 00:01.3 chip-ID: 8086:7113
    class-ID: 0680
  Device-2: Red Hat Virtio network driver: virtio-pci v: 1 port: c040
    bus-ID: 00:03.0 chip-ID: 1af4:1000 class-ID: 0200
  IF: ens3 state: up speed: -1 duplex: unknown mac: <filter>
Drives:
  Local Storage: total: 40 GiB used: 12.45 GiB (31.1%)
  ID-1: /dev/sda vendor: QEMU model: HARDDISK size: 40 GiB speed: <unknown>
    type: N/A serial: <filter> rev: 2.5+ scheme: GPT
Partition:
  ID-1: / size: 38.58 GiB used: 12.45 GiB (32.3%) fs: ext4 dev: /dev/sda3
  ID-2: /boot/efi size: 512 MiB used: 5.2 MiB (1.0%) fs: vfat
    dev: /dev/sda2
Swap:
  ID-1: swap-1 type: file size: 1.83 GiB used: 0 KiB (0.0%) priority: -2
    file: /swapfile
Sensors:
  Message: No sensor data found. Is lm-sensors configured?
Repos:
  Packages: 2277 apt: 2272 flatpak: 5
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/google-chrome.list
    1: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http://packages.linuxmint.com vanessa main upstream import backport
    2: deb http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
    3: deb http://archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http://security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
Info:
  Processes: 185 Uptime: 17m wakeups: 837 Memory: 3.83 GiB
  used: 1.65 GiB (43.1%) Init: systemd v: 249 runlevel: 5 Compilers:
  gcc: 11.2.0 alt: 11 Shell: Sudo (sudo) v: 1.9.9 default: Bash v: 5.1.16
  running-in: gnome-terminal inxi: 3.3.13

**Comment by LinuxOnTheDesktop** [comment]
Did you misformat, and mislabel, the 'Screenshots' section? That section contains much crossing-out and no screenshots.

I might be worth noting the following points as well. Elisa is a music player. Just now I installed it on Mint 20.3 Cinnamon and it did _not_ crash on startup. (I have not tried it on the beta of Mint 21.)

**Comment by mtwebster** [comment]
Can you install 'phonon4qt5-backend-vlc' and try this? That resolved this crash for me.

https://bugs.launchpad.net/ubuntu/+source/elisa-player/+bug/1881741

edit: changed package name to install

**Comment by mtwebster** [comment]
Closing as this is a dependency problem with the elisa package and a report is already open for it upstream.

**Comment by RTinIB** [comment]
Michael, I couldn't include a screenshot because elisa crashed immediately with no graphics output.

After installing vlc, elisa started without any problem.
