### ISSUE TITLE
 [Xfce-21-Beta] Screen flickering problem on particular point when I move the cursor .

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint21-beta#122]
I was testing Mint Xfce-21-Beta.Screen flickering problem started on a particular point when I move the cursor.Please watch the Video and check the cursor position.

https://user-images.githubusercontent.com/87972205/179920430-8f78dd2e-263b-4265-a7ef-ecd92d598c70.mp4

**Comment by clefebvre** [comment]
wow.. this looks like an xorg or video driver rendering issue. I hope it's not hardware related.

I can't do much without knowing what's causing this though or what's responsible for it. If it continues to happen I'd suggest troubleshooting the issue, trying to see in which conditions and with which particular components it happens or doesn't happen, so you eventually identify what's causing it.
