### ISSUE TITLE
[Cinnamon] Feature request  nemo-media-columns

### ISSUE THREAD

**Issue by SimonIremonger** [linuxmint/mint21-beta#123]
Please consider including  nemo-media-columns  on Cinnamon systems by default so that users can turn on "EXIF Date" column, parity with windows file manager had the picture-date feature for decades.
I would actually like to see Nemo have a "media summary" column which uses the column for different things depending on the filetype.

**Comment by clefebvre** [comment]
Added to roadmap. We need to review performance impacts to doing that.
