### ISSUE TITLE
All versions -- zram-config feature request

### ISSUE THREAD

**Issue by SimonIremonger** [linuxmint/mint21-beta#124]
Please look into  installing package  zram-config  by default.  In every way I can tell across 64bit-systems small and large, slow and fast, this almost always improves matters, reduces swap-to-disk load (SSD wear and hard disk latency).  zram has matured well and seems better than zswap setups.

The 22.04 zram-config package seems to have sensible conservative defaults (could be set larger...?) and co-exists gracefully as higher-priority to actual swap file (arguably the swapfile can be removed on all but the lowest-ram systems).
I think this should be installed-by-default at least for mint 21.1 onwards, if not mint21 release.

This is especially helpful in this era of memory-hogging containerized packages, electron apps, chromium, and so-on, a huge gain for no work, just change in default packages.   Could be helpful to further test the default-sizes for further optimization, but this is not a reason not to include.
MAYBE on really old/slow 64bit cpus with fast-SSD (a rare combination) the tradeoff of cpu to disk is not the best, but this is very minor in comparison with the performance benefit for almost everybody.

**Comment by arthurgomespassos** [comment]
I think that's a good idea too

**Comment by clefebvre** [comment]
Added to roadmap.
