### ISSUE TITLE
[all versions] Thunderbird collaboration with upstream.

### ISSUE THREAD

**Issue by SimonIremonger** [linuxmint/mint21-beta#125]
On all Mint21-versions, please consider collaboration with Mozilla/MZLA on Thunderbird, in the same way as you do for Firefox already.
Alas Ubuntu Thunderbird packages have been slow to catch-up with important security-updates.
Additionally, it would be (in my view) much better if this new-release had Thunderbird 102 from the get-go  (a considerable change/upgrade on the mint 91, including Matrix support and a lot of other redesign/aspects), personally I think Mint-21 users ought not need to go through the change to 102 "later".
I appreciate this may only be possible for mint 21.1 but do consider how this could be considered or planned through the life of mint-21.x generally.

**Comment by clefebvre** [comment]
Thanks. This is not planned at the moment.
