### ISSUE TITLE
Mint 21 Updated radeon packages for Release image.

### ISSUE THREAD

**Issue by SimonIremonger** [linuxmint/mint21-beta#127]
For mint-21 release image, please include this update jammy-updates (22.04LTS updates) packages:-
xserver-xorg-video-radeon  1:19.1.0-2ubuntu1
xserver-xorg-video-ati     1:19.1.0-2ubuntu1
[Note these might not automatically install yet due to 'phasing' mechanism introduced in ubuntu]
This fixes issue with Radeon display rotation (at least) crash when running from live image, which is particularly annoying if you have vertical monitor(s) and want to install linux-mint!.

**Comment by clefebvre** [comment]
Sorry @SimonIremonger we don't update the base during BETA. We will however produce an EDGE image later though, also with an HWE kernel.
