### ISSUE TITLE
All versions, trivial PcMemtest provision for mint-21-release iso

### ISSUE THREAD

**Issue by SimonIremonger** [linuxmint/mint21-beta#128]
Please look at including on the mint-21 release ISO image both:-
/boot/pcmemtest.bin    [replacing, or in addition to memtest86+.bin for legacy-booting memtest]   This seems to be better to me.
/boot/pcmemtestx64.efi    **IMPORTANT** this now allows FOSS memtest to work on EFI systems from the linux mint boot image, put "Memory Test" back in the EFI boot menu list with a  'linuxefi' or equivalent boot entry.

Both these files can be found from the Ubuntu 22.04 'pcmemtest' package, which is an improved fork of older memtest86+, which has been accepted back into FOSS memtest project now.

Note, r.e. *installed* 22.04 systems, that 'pcmemtest' package itself attempts to detect EFI booting is available, and thus doesn't correctly set up bootability of pcmemtest.bin for legacy-booted systems, given that the new installer always sets up hybrid bootablity with EFI as well.
This scripting-oversight does not, in any way, preclude including pcmemtest on the Linux Mint 21 release .iso which would be a very low regression-potential addition that doesn't affect installer or installed-systems in any way.

**Comment by clefebvre** [comment]
Add to the roadmap for consideration in Mint 21.1.

**Comment by Fantu** [comment]
some infos:
pcmemtest was not developed anymore and package will be removed as was merged into memtest86+ v6
memtest86+ v6 is developed by initial memtest86+ developer + pcmemtest developer and another; started on pcmemtest, added some features missed in pcmetest that was present in older memtest86+ and other improvements/fixes
v6 beta3 is in debian experimental for now (maintained by me and pcmemtest maintainer), actually v6 it is in feature freeze and final release will be released probably in 4-6 weeks. any help to test/improve memtest86+ v6 package is appreciated
on final release we'll migrate to debian unstable and after migration to testing if there isn't important issue I want do a backport to bullseye and jammy
