### ISSUE TITLE
Sublime-text Debian package is from the Development Channel

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/mint21-beta#129]
Since it is no longer in Ubuntu 22.04 as a Debian package, Linux Mint provides the Development Channel version 4131 as part of the 'mint-dev-tools' package.

In Linux Mint 20.3 (Una) sublime-text_4126_amd64.deb was provided.  The Stable Channel, Build 4126.

The issue is the Development Channel version does not allow unlimited evaluation.  Right away it asks for a license key.  Making it unusable for most.

Any chance we could get this fixed for those who just want to use Sublime as a stand-alone?
Right now the work around is to grab the sublime-text_4126_amd64.deb from the Una repository and install it.

**Comment by JosephMcc** [comment]
I noticed this one as well. You can also just grab the .deb from the Sublime Text website.

**Comment by clefebvre** [comment]
Well spotted.

Back to stable version.
I also update sublime-merge while I was at it.
