### ISSUE TITLE
[Cinnamon] Auto-hidden panel SOMETIMES does not come out of hiding.

### ISSUE THREAD

**Issue by spamegg1** [linuxmint/mint21-beta#13]
It seems to depend on what applications are in the System Tray. 

Often it works fine, here is a video of it working properly:
[cinnamon-2022-07-14:19:21:22.webm](https://user-images.githubusercontent.com/4255997/179030395-d96c1958-abc1-49a1-98b9-d512b3615470.webm)

I first discovered the issue when Deadbeef is minimized to System Tray, and the Sound Tray applet is removed. Here is a video:
[cinnamon-2022-07-14:19:25:57.webm](https://user-images.githubusercontent.com/4255997/179031117-5ae6cee0-8f79-4416-b52b-1b96d40ed0d6.webm)
If I select the "Hide system tray icon" option in Deadbeef settings, the problem goes away.

I thought the issue might be limited to Deadbeef. But it also happened with Deluge. Here is a video:
[cinnamon-2022-07-14:19:30:35.webm](https://user-images.githubusercontent.com/4255997/179031911-a3d6c5b3-33b8-445b-bb71-e8a71826c434.webm)

Very interestingly, if I change Deluge's tray setting from "SysTray" to "AppIndicator" then the problem goes away. Maybe that can be helfpul. Here is a video:
[cinnamon-2022-07-14:19:32:15.webm](https://user-images.githubusercontent.com/4255997/179032326-d5685096-cf7f-4b20-b919-5402ee732eab.webm)

**Comment by mtwebster** [comment]
Fixed:
https://github.com/linuxmint/cinnamon/commit/909cfb098876a5d36290dc82df97e0c48e54efa
https://github.com/linuxmint/cinnamon/commit/909cfb098876a5d36290dc82df97e0c48e54efa

**Comment by spamegg1** [comment]
Great! I suppose we can expect these fixes soon, like a few days?

**Comment by mtwebster** [comment]
Yes, possibly tomorrow.

**Comment by spamegg1** [comment]
Can confirm it's fixed in Cinnamon 5.4.3
