### ISSUE TITLE
[Mate] Display sleeps even though preference is set to "Never"

### ISSUE THREAD

**Issue by vic9psgit** [linuxmint/mint21-beta#130]
On Mint 21 Beta MATE LiveDisc, the display falls asleep upon 10 minutes of inactivity, even though "Put display to sleep when inactive for" is set to "Never" in the "Power Management" control panel.  This problem occurs, if the computer is isolated from the Internet and LAN and if the automatic adjustment of the current time of the system clock is prevented because of the unavailability of the synchronization to time servers on the Internet.

This problem does not occur if the computer is connected to the Internet and if the current time of the system clock is constantly adjusted by the synchronization to time servers on the Internet.

Moreover, this problem does not occur on an installed Mint (as opposed to LiveDisc), even if the computer is isolated from the Internet.

This is not an intermittent problem; I can always reproduce the problem by the following steps.

### To Reproduce

Before booting, physically isolate the computer from LAN and the Internet.

(For the purpose of reproducing this issue, it is recommended to use a desktop PC which lacks any wireless connectivity including Wifi and Bluetooth.  For such a desktop PC, unplugging the Ethernet cable easily isolates the computer from LAN and the Internet.  If a notebook PC with wireless connectivity is used, it is difficult or impossible to "physically isolate the computer from LAN and the Internet" before booting, while booting, and immediately after booting, unless BIOS can disable wireless connectivity in advance.)

Boot to the LiveDisc.

As soon as the booting of Mint 21 Beta MATE LiveDisc completes, configure the Screensaver and the Power Management as follows.

Note that blank brackets [ ] indicates "unchecked"
and that v-holding brackets [v] indicates "checked".

    Control Center > Look and Feel >

      Screensaver

        Regard the computer as idle after:  2 hours

        [ ]  Activate screensaver when computer is idle
        [ ]  Lock screen when screensaver is active

    Control Center > Hardware >

      Power Management

        On AC Power tab

          Actions
            Put computer to sleep when inactive for:  Never

          Display
            Put display to sleep when inactive for:   Never

        General tab
          Actions
            When the power button is pressed:    Suspend
            When the suspend button is pressed:  Suspend

Disconnect the USB keyboard and mouse from the computer.

Let the computer stay idle, and wait for 11 minutes.

### Expected Result

The display never sleeps.

### Actual Result

The display falls asleep after 10 minutes of idleness.

### Consideration

This Mint 21 Beta MATE LiveDisc is read-only and was made from "linuxmint-21-mate-64bit-beta.iso" verbatim without any modification.  The sha256 digest of the iso image is

    f10fb697d2fd3d601c016cac471aeb19c419cdc2dc71ba16e31ce47d5ee149d7

I tested also on an installed Mint, and found that this problem does not occur on an installed Mint, but occurs only on LiveDisc.  I guess that LiveDisc may be less thoroughly tested than an installed OS.  While a problem on an installed OS may sometimes be difficult to reproduce because of too much customization of settings, a problem on LiveDisc must be easier to reproduce because of no customization.

This problem has been persistent on MATE Mint 20.1 through 20.3, and 21Beta.  In contrast, *Ubuntu* MATE 20.04.3 LiveDisc is free from this problem.  It is unknown whether Mint versions prior to 20.1 had this problem.

On the "Power Management" control panel, the default value for "Put display to sleep when inactive for" is 30 minutes.  On the "Screensaver" control panel, the default value for "Regard the computer as idle after" is "5 minutes".  However, the display falls asleep upon "10 minutes" of idleness.  I wonder where this "10 minutes" come from.  Perhaps, "30 minutes" may be the default on the configuration file in "/etc" or "/lib", and "10 minutes" may be the hard-coded default.  Anyway, I do NOT want the display to fall asleep.

To reproduce the problem, an AC-operated desktop/tower computer may be a better subject than an battery-operated notebook/laptop.

### Another Experiment

Instead of setting "Put display to sleep when inactive for" to "Never" in the "Power Management" control panel, I also tested to see what will happen if the "Power Management" control panel is entirely left untouched and if only the "Screensaver" is changed as above.  The expect result is that the display falls asleep upon "30 minutes" of idleness, because "30 minutes" is the default on the control panel.  However, the actual result is that the display falls asleep upon "10 minutes" of idleness.

**Comment by clefebvre** [comment]
Hi @vic9psgit,

If it works in Ubuntu MATE 22.04 I would suggest to compare the versions of the MATE packages. The version of mate-power-manger in Mint 21 is the same as 22.04 with the following commits on top https://gitlab.com/mint-pins/mate-power-manager/-/commits/master. As you can see these only affect the panel icon.

Maybe Ubuntu MATE 22.04 applies patches or a version which isn't in 22.04?

Other than that it could be a difference in the configuration between Mint and Ubuntu MATE, but in this case I'd still consider it a bug that the software doesn't behave as expected.

I'd suggest to track this upstream directly by reporting the issue to the MATE project. https://github.com/mate-desktop/mate-power-manager
