### ISSUE TITLE
[Cinnamon] Video file thumbnailer crashes on MP4 files when Totem is installed.

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/mint21-beta#133]
This issue is solid repeatable and has been observed during the entire Beta.
It is routine that Totem is added to a system already installed on a drive.
It does not occur in Linux Mint 20.3 or LMDE 5, both of which have Totem installed.
Between each crash, deleted all the thumbnail files.
Looking at the dump, which occur every time a directory with MP4 files are opened in Nemo, led to believe that Totem was somehow the cause.
Booted from the Beta ISO USB and thumbnailing works as expected.
Removing Totem and clearing the thumbnail cache and thumbnailing worked on MP4 files as expected on the installed system.

Here are several crash logs and they seem to be consistent.
https://termbin.com/mu20
https://termbin.com/bqaq

While one would not expect this to be fixed in time for the end of the Beta (it might be an upstream issue) just wanted to be sure it was reported for reference.

**Comment by Acheron17** [comment]
Just completed a fresh install and loaded all the software packages including Totem and there was no issue.  Wondering if there was a stale package in the 22.04 repository or just a corrupted library.

**Comment by clefebvre** [comment]
This is clearly a bug in totem, more specifically in the thumbnailer it provides. This should be reported upstream directly.

**Comment by Acheron17** [comment]
Yes I would agree.  Been working with this all night and removing Totem seems to stop the failure when it starts.  Thank you.
