### ISSUE TITLE
[Cinnamon] Window tiling and edge snapping do not work in rotated display

### ISSUE THREAD

**Issue by sudorook** [linuxmint/mint21-beta#134]
(Not sure whether to report here or in linuxmint/cinnamon...)

Distro: Arch Linux
Version: 5.4.4-1

I use an external monitor, and when I have the display rotated, window tiling/snapping does not work. Curiously, it does when in a normal rotation. See GIF below:

[Peek 2022-07-21 17-22.webm](https://user-images.githubusercontent.com/6200846/180326164-c8e12c5d-c6d8-4c68-b0fe-eb34af827d5b.webm)

(The `rotate` command is a [wrapper script](https://github.com/sudorook/misc-scripts/blob/master/rotate) for using `xrandr`.)

No idea what is causing this.

I should also note that in previous releases of 5.4, keyboard shortcuts worked but dragging windows to tile/snap them did not. It was only until 5.4.4 that neither did.

**Comment by JosephMcc** [comment]
Since you are on Arch you should really report this on linuxmint/cinnamon.
