### ISSUE TITLE
[Cinnamon] gnome-terminal Edit->Select all selected all with history now only the displayed

### ISSUE THREAD

**Issue by KAMI911** [linuxmint/mint21-beta#135]
**Describe the bug**
There is a difference how Edit -> Select all behaves in gnome-terminal.
The old method was (version 3.36.2, with VTE 0.60.3) Edit -> Select all action selected all the terminal text WITH history.
The new method in Linux Mint 21 (Cinnamon) is (version 3.44, with VTE 0.68) Edit -> Select all action selected all the terminal text WITHOUT history.

Please bring back the old method, or at least add a new Edit menu action as Select visible for new method and bring back Select all as separated menu action. Thank you!

**To Reproduce**
0. Start gnome-terminal in Linux Mint 20 and 21, fill up the terminal more text than it can display without scrolling.
1. Go to 'Edit' 
2. Click on Select all'
3. Paste the content to a xed.
4. You can see the differences in Linux Mint 20's and 21's gnome-terminal.

**Expected behavior**
It would be nice if there were action for both Select all and Select visible in gnome-terminal.

**Comment by clefebvre** [comment]
This is an upstream bug. It's tracked at https://bugs.launchpad.net/ubuntu/+source/vte2.91/+bug/1922276.
