### ISSUE TITLE
performance suggestion

### ISSUE THREAD

**Issue by arthurgomespassos** [linuxmint/mint21-beta#137]
Google Translator: You have added zram-config to the roadmap, so I was wondering if you are going to change the default values of vm.vfs_cache_pressure, vm.swappiness, vm.dirty_background_ratio and vm.dirty_ratio of the system to have better performance together with zram, since mainly higher swappiness and higher cache pressure are settings that I see many linux users say is good when using zram.

**Comment by clefebvre** [comment]
Thanks, we don't know yet. It's in the roadmap so we have a look at it. No decision was taken yet. I added a link to your issue as well.
