### ISSUE TITLE
[Cinnamon] Hypnotix screen being watched will not shut down. Must close the whole program

### ISSUE THREAD

**Issue by kangal3632** [linuxmint/mint21-beta#138]
**Describe the bug**
When you open Hypnotix and select either a TV channel or a movie, a secondary screen opens. The show/movie plays but when you want to close the secondary screen neither the "close" button in the upper right corner nor the "close" selection on the panel icon will close the secondary screen.  Have to shut Hypnotix down and reopen.

**To Reproduce**
1. Open Hypnotix
2. Select either a TV or movie selection
3. Once the secondary screen open, stop the show/film
4. Push the "close" button in the upper right
5. Nothing happens
6. Right click on the Hypnotix icon on the panel and select "close"
7. Nothing happens
8. Must go the the main Hypnotix window and shut down from there.

**Expected behavior**
I would expect the "close" button on the secondary screen to close the screen so I can make another selection from the main Hypnotix screen

**Screenshots**
If applicable, add screenshots to help explain your problem: screen shot attached below

**Hardware and mintUpdate**
* If relevant, you could provide `inxi -Fxxxrz` 
* System:
  Kernel: 5.15.0-41-generic x86_64 bits: 64 compiler: gcc v: 11.2.0
    Desktop: Cinnamon 5.4.5 tk: GTK 3.24.33 vt: 7 dm: LightDM 1.30.0
    Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy
Machine:
  Type: Kvm System: QEMU product: Standard PC (i440FX + PIIX, 1996)
    v: pc-i440fx-focal serial: <superuser required> Chassis: type: 1
    v: pc-i440fx-focal serial: <superuser required>
  Mobo: N/A model: N/A serial: N/A BIOS: SeaBIOS v: 1.13.0-1ubuntu1.1
    date: 04/01/2014
CPU:
  Info: quad core model: Intel Core i5-1035G1 bits: 64 type: MT MCP
    smt: enabled arch: Ice Lake rev: 5 cache: L1: 512 KiB L2: 16 MiB L3: 16 MiB
  Speed (MHz): avg: 1190 min/max: N/A cores: 1: 1190 2: 1190 3: 1190
    4: 1190 5: 1190 6: 1190 7: 1190 8: 1190 bogomips: 19046
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Red Hat QXL paravirtual graphic card driver: qxl v: kernel ports:
    active: Virtual-1 empty: Virtual-2,Virtual-3,Virtual-4 bus-ID: 00:02.0
    chip-ID: 1b36:0100 class-ID: 0300
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: N/A
    unloaded: fbdev,modesetting,vesa gpu: qxl note:  X driver n/a
    display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 96 s-size: 508x286mm (20.0x11.3")
    s-diag: 583mm (23")
  Monitor-1: Virtual-1 res: 1920x1080 hz: 60 size: N/A modes: max: 1024x768
    min: 640x480
  OpenGL: renderer: llvmpipe (LLVM 13.0.1 256 bits) v: 4.5 Mesa 22.0.1
    direct render: Yes
Audio:
  Device-1: Intel 82801FB/FBM/FR/FW/FRW High Definition Audio
    vendor: Red Hat QEMU Virtual Machine driver: snd_hda_intel v: kernel
    bus-ID: 00:04.0 chip-ID: 8086:2668 class-ID: 0403
  Sound Server-1: ALSA v: k5.15.0-41-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel 82371AB/EB/MB PIIX4 ACPI
    vendor: Red Hat Qemu virtual machine type: network bridge
    driver: piix4_smbus v: N/A port: N/A bus-ID: 00:01.3 chip-ID: 8086:7113
    class-ID: 0680
  Device-2: Realtek RTL-8100/8101L/8139 PCI Fast Ethernet Adapter
    vendor: Red Hat QEMU Virtual Machine driver: 8139cp v: 1.3 port: c000
    bus-ID: 00:03.0 chip-ID: 10ec:8139 class-ID: 0200
  IF: ens3 state: up speed: 100 Mbps duplex: full mac: <filter>
Drives:
  Local Storage: total: 49.43 GiB used: 10.08 GiB (20.4%)
  ID-1: /dev/sda vendor: QEMU model: HARDDISK size: 49.43 GiB
    speed: <unknown> type: N/A serial: <filter> rev: 2.5+ scheme: GPT
Partition:
  ID-1: / size: 47.86 GiB used: 10.07 GiB (21.0%) fs: ext4 dev: /dev/sda3
  ID-2: /boot/efi size: 512 MiB used: 5.2 MiB (1.0%) fs: vfat
    dev: /dev/sda2
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 0 KiB (0.0%) priority: -2
    file: /swapfile
Sensors:
  Message: No sensor data found. Is lm-sensors configured?
Repos:
  Packages: apt: 2119
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http://packages.linuxmint.com vanessa main upstream import backport
    2: deb http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
    3: deb http://archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http://security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
Info:
  Processes: 212 Uptime: 17m wakeups: 198 Memory: 3.76 GiB
  used: 990.4 MiB (25.7%) Init: systemd v: 249 runlevel: 5 Compilers:
  gcc: 11.2.0 alt: 11 Shell: Bash v: 5.1.16 running-in: gnome-terminal
  inxi: 3.3.13

* Is your system all up-to-date ? System is up to date

**Additional context**
I am running Linux Mint 21-Beta on a Gnome Boxes virtual machine on Linux MInt 20-3.  I reported problems with LMDE-5 and most turned out to be issues with Gnome Boxes so this may be the same
![Hypnotic 2022-07-23 16-52-24](https://user-images.githubusercontent.com/100831976/180609308-7dd9d4e8-5ff5-42b6-a7e6-e76f3512c29e.png)

**Comment by clefebvre** [comment]
This is an issue with virtualization and libmpv, it's known and tracked at https://github.com/linuxmint/hypnotix/issues/198.
