### ISSUE TITLE
Booting takes a long time

### ISSUE THREAD

**Issue by ruldc** [linuxmint/mint21-beta#140]
Hello!
First of all, I want to thank you for all your work and contribution to this wonderful project!
Until now I have used the version of Linux 18.3, which for me worked flawlessly, but I made the transition to 20.3, it works well, but compared to the version of Linux 18.3, it is very difficult to boot.
I downloaded the iso image with the beta version "vanessa" thinking that it will run more fluently but it moves even harder, the computer is not to blame because I have an intel i5 processor and 8gb ram, tested on windows 10 it boots in about 14 seconds, but I think that this problem can be solved with the loading time of the system to boot faster in linux...
I'm a Linux fan and I've been using it on my personal PC for several years, I'm very happy with Linux, I gave up Windows in favor of this wonderful system!
Please if you can do something to reduce the boot time of the system at startup in the future version of linux 21.
Thank you very much, and I hope this problem can be solved, all the best!!

**Comment by clefebvre** [comment]
Duplicate: https://github.com/linuxmint/mint21-beta/issues/36
