### ISSUE TITLE
(intentional?) When moving or copying file(s) into Nemo/Thunar from the desktop or from one Nemo/Thunar window to another, the destination Nemo/Thunar window does not get selected (e.g. Ctrl+a highlights source folder)

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21-beta#141]
(tested in a live session of Cinnamon and Xfce as well as a fully-updated local installations of both as of 2022-07-15... though I suppose that's a bit outdated now)

**Describe the bug**
When you are moving or copying file(s) into Nemo/Thunar from the desktop or from one Nemo/Thunar window to another, the destination Nemo/Thunar window does not get selected (e.g. Ctrl+a highlights source folder).

This may be an intentional design decision, but it's difficult for me to tell.

**To Reproduce**
1. boot Mint 21 beta
2. create a new file or folder on the desktop
3. open the `Home` folder
4. move or copy the newly-created file from step 2 into the `Home` folder
5. press Ctrl+a
6. observe how it highlights all of the files on the desktop rather than all of the files in the `Home` folder

**Expected behavior**
After performing step 5, I would have expected that all of the files in the `Home` folder would be selected.

**Additional context**
This may very well be intentional behavior and my recent history of daily-driving Windows for the last 15 years is simply showing itself.

**Comment by clefebvre** [comment]
This is intentional. It's the same when moving from window A to window B, you're currently manipulating window A so it has and retains focus. You might want to move more items, it's consistent with the way it works with multiple windows.
