### ISSUE TITLE
Nemo & Thunar - file names with 〜 or ー or ／ unicode characters cause entire file name to shift vertically, causing file names to shift up or down depending on whether the offending unicode character is present/visible or not

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21-beta#143]
(tested in a live session of Cinnamon and Xfce as well as a fully-updated local installations of both as of 2022-07-15... though I suppose that's a bit outdated now)

**Describe the bug**
In both Nemo and Thunar, any files with 〜 or ー or ／ unicode characters (do not confuse them for their ANSI equivalents of `~`, `-`, and `/`) in their file name causes the entire file name itself shift vertically, causing files to shift up or down depending on whether the offending unicode character is present/visible or not.

This occurs in all views but is really noticeable in "List View" by simply shinking the 'Name' header to hide and show the offending unicode character, though you can similarly just rename a file and then delete and re-paste the according unicode character to see a similar change (it even occurs in the pop-up window that Thunar uses for renaming).

**To Reproduce**
1. boot Mint 21 beta
2. open the `Home` folder
3. create a new file or folder with a file name of something like `file name ／ test testing`
4. during the renaming process, highlight specifically only the unicode character and to a Ctrl+x
5. observe how the file name shifted vertically
6. paste the previously-copied unicode character
7. observe how the file name shifted vertically in the opposite direction compared to step 5

**Expected behavior**
I would not expect file names to shift vertically based on what characters are present in their file names considering that no shifting occurs regardless of whether a file name is `- - -` (hyphens) or `l l l` (lowercase Ls)

**Screenshots**
(this is animated; wait a couple seconds and pay attention to the second-from-bottom listed file)
![animated](https://user-images.githubusercontent.com/11896003/180616094-6e4199da-d3d2-4c5b-a19b-ef4a6fc222dc.png)

**Comment by clefebvre** [comment]
I think this is just the result of ／ taking more vertical space and making the label higher than before. I can reproduce it in Glade:

![image](https://user-images.githubusercontent.com/1138515/180617329-1e403525-c66e-40af-915e-8289b320a206.png)

It's either upstream in Gtk or down to the font itself. Thunar and Nemo both are in Gtk and both use system fonts. It probably happens in Caja and all Gtk.Label widgets showing text.

**Comment by NintendoManiac64** [comment]
I guess I should have used 〜 in the example then because it happens with it as well despite the fact that you'd not expect it to take up more vertical space... yet it does.
