### ISSUE TITLE
[Xfce] Onboard - left-clicking status icon shows context menu instead of directly hiding or showing Onboard

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21-beta#145]
(tested in a live session of Xfce as well as a fully-updated local Xfce installation as of 2022-07-15... though I suppose that's a bit outdated now; I also tested on live Cinnamon, installed Cinnamon, and even live Xubuntu 22.04 but this issue _only_ seems to occur on Mint Xfce).

**Describe the bug**
When "Show the status icon" is enabled for Onboard, left-clicking on the corresponding status icon shows the context menu instead of directly hiding or showing Onboard.

**To Reproduce**
1. boot Mint 21 beta Xfce
2. open Onboard
3. left-click on the status icon for Onboard
4. observe how the context menu appeared
5. press the Esc key on your keyboard
6. right-click on the status icon for Onboard
7. observe how the context menu also appeared

**Expected behavior**
Just like in Cinnamon and Xubuntu 22.04, left-clicking Onboard's status icon should be a direct toggle for hiding and showing Onboard without the context menu appearing.

**Additional context**
I would give screenshots but I don't know how to visually display a right or left-click action

**Comment by clefebvre** [comment]
It looks like middle-click performs the same action in Xfce Xapp applet as left-click in Cinnamon Xapp applet.

**Comment by clefebvre** [comment]
Ah sorry my mistake. Onboard doesn't show up in the Xapp tray, it shows up in the Status applet. Looking at the code it uses a Gtk.StatusIcon, so that's upstream from us. It's up to Xfce to decide how to implement the primary action in this applet.

I think what will happen eventually though is that we'll take over the maintenance of our visual keyboards. For now though, this is a wontfix.

**Comment by NintendoManiac64** [comment]
> Looking at the code it uses a Gtk.StatusIcon, so that's upstream from us. It's up to Xfce to decide how to implement the primary action in this applet.

Then why does left-click function as expected in Xubuntu 22.04?

**Comment by clefebvre** [comment]
Do they use the same applet or an indicator applet?

**Comment by NintendoManiac64** [comment]
> Do they use the same applet or an indicator applet?

Oh uh, I have no idea.  That being said, the icon is different which might give a hint.

**Comment by mtwebster** [comment]
I think their status applet also supports StatusNotifier - onboard used appindicator which uses the StatusNotifier interface. One difference however is that appindicator has no conception of left-click activation.  They use middle-click instead (but not always). Onboard is one that does use middle-click

In our xapp applet, we have onboard on a list:
![image](https://user-images.githubusercontent.com/262776/180856428-acd5367b-7027-4a9b-92bf-6f0d564d2211.png)
We modify the behavior to have left-click activates the middle-click action.  This is why it works in Cinnamon.
