### ISSUE TITLE
[Cinnamon] 125% scaling Ideapad 3 14"

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint21-beta#146]
Start Menu not scaling correctly 125%. Everything else scales just fine but not the menu.

**Comment by LinuxOnTheDesktop** [comment]
I imagine that the devs will want you to use the issue template. For, you are not giving anyone much to go on here.

**Comment by clefebvre** [comment]
No it's ok. It's a known issue, it was already reported and moved towards Cinnamon as a feature request. The idea is to restart cinnamon after the new scaling is confirmed. https://github.com/linuxmint/cinnamon/issues/10958
