### ISSUE TITLE
[Xfce] Onboard - flickers when resizing horizontally if partially off left or right side of the screen OR over the bottom panel; same for resizing vertically if partially off the top of the screen

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21-beta#147]
(tested in a live session of Xfce as well as a fully-updated local installation as of 2022-07-15... though I suppose that's a bit outdated now; I also tested on live Cinnamon, installed Cinnamon, and even live Xubuntu 22.04 but this issue only seems to occur on Mint Xfce).

**Describe the bug**
Onboard flickers when resizing horizontally if partially off left or right side of the screen OR over the bottom panel; Onboard will also flicker when resizing vertically if partially off the top of the screen.

**To Reproduce**
1. boot Mint 21 beta Xfce
2. open Onboard
3. move it so that it is partially off the left side of the screen
4. resize onboard horizontally
5. observe the flickering
6. move onboard so that it is partially off the right side of the screen
7. resize onboard horizontally
8. observe the flickering
9. move onboard so that it is partially over-top of the bottom panel without being off the bottom of the screen (though the issue will still occur even if it's partially off the bottom of the screen)
10. resize onboard horizontally
11. observe the flickering
12. move onboard so that it is partially off the top part of the screen
13. resize onboard horizontally (not a typo)
14. observe the flickering
15. move onboard to the center of the screen
16. move onboard so that it is partially off the top part of the screen
16. now resize onboard _vertically_
17. observe the flickering

**Expected behavior**
Onboard should either straight-up not flicker (like it does on Xubuntu 22.04 when `Dock to screen edge` is unchecked) or behave like on Cinnamon where you cannot even position Onboard over the bottom panel nor partially off-screen.

**Screenshots**
Due to the flickering nature, I'm posting the corresponding APNG as a link instead:
- https://user-images.githubusercontent.com/11896003/180623384-3645ae08-dec9-4bcc-95a7-651725fd5e55.png

**Additional context**
This occurs in both VirtualBox and on real-world Ryzen 4800U integrated graphics hardware, so this isn't a GPU driver-related type of flicker.

**Comment by clefebvre** [comment]
Confirmed. This should be reported upstream to onboard directly.

**Comment by NintendoManiac64** [comment]
> This should be reported upstream to onboard directly.

Even though it does not occur in Xubuntu 22.04?

**Comment by clefebvre** [comment]
Yes. It might have to do with compositing or some WM settings, but it's still something for onboard to investigate imo.
