### ISSUE TITLE
[Cinnamon] Cinnamon crashes when virtual keyboard is used with alternate language

### ISSUE THREAD

**Issue by MichelHanzen** [linuxmint/mint21-beta#149]
**Describe the bug**
I have defined two keyboards, Belgian (for me) and Thaï (for my wife). When I used the virtual keyboard with the Belgian keyboard, the virtual keyboard works correctly, though a qwerty keyboard is displayed. Now, I close the virtual keyboard. I switch to the Thaï keyboard. If I want to use the virtual keyboard again, cinnamon crashes as soon as I press a key on the virtual keyboard. Moreover, the virtual keyboard layout is the Belgian one.

**To Reproduce**
See above

**Expected behavior**
The virtual keyboard should reflect the keyboard layout selected and Cinnamon should not crash.

**Screenshots**
None

**Hardware and mintUpdate**
N/A

**Additional context**
None

**Comment by clefebvre** [comment]
Crash fixed in caribou 0.4.21+mint4+vanessa.
