### ISSUE TITLE
[Cinnamon] Thumbnail list of grouped windows with cinnamon theme transparent background.

### ISSUE THREAD

**Issue by Initu-Castilhos** [linuxmint/mint21-beta#153]
Thumbnail list of grouped windows with cinnamon theme transparent background.
As the image below shows.

![linuxmint21](https://user-images.githubusercontent.com/59381215/180673816-23e69b5f-a381-4a94-a3a5-b992be72099f.png)
![Captura de tela de 2022-07-24 21-55-02](https://user-images.githubusercontent.com/59381215/180674008-66bf7622-8ab7-4bfc-98af-4d9c741631cf.png)

**Comment by fredcw** [comment]
The cinnamon (desktop) theme you're using needs to be updated. Which theme are you using?

**Comment by Initu-Castilhos** [comment]
GTK: Adwaita;
 Icons: Adwaita;
Desktop: cinnamon (system default).

**Comment by JosephMcc** [comment]
I could have sworn I fixed this but apparently not. I'll look again.

**Comment by JosephMcc** [comment]
Ok, it seems I missed some of it. This should fix the rest: https://github.com/linuxmint/cinnamon/pull/10963
