### ISSUE TITLE
continuation of #150

### ISSUE THREAD

**Issue by king-dahmanus** [linuxmint/mint21-beta#154]
I made this one because I was unsure of people recieving my replies on a closed issue, so I'm continuing it. Instead of auto enabling it by default, you could have a script that activates after orca is enabled, thereby enabling it only when necessary

_Originally posted by @king-dahmanus in https://github.com/linuxmint/mint21-beta/issues/150#issuecomment-1193944937_

**Comment by clefebvre** [comment]
MATE and Cinnamon have a settings daemon dedicated to A11Y which does exactly that. When you enable accessibility options in the DE their job is to not only provide required tools at DE level, but also to let apps know what you need.

**Comment by king-dahmanus** [comment]
do they enable the same variables I talked about in #150 ?

**Comment by clefebvre** [comment]
I don't know @king-dahmanus. If you think they should and find out they don't please report the issue respectively in https://github.com/linuxmint/cinnamon-settings-daemon or https://github.com/mate-desktop/mate-settings-daemon.

Make sure you justify the use of each variable. Explain why they're needed, what software they affect and how they affect it. Most developers have zero experience with A11Y so these explanations are key for them to understand the issue and reproduce it.
