### ISSUE TITLE
[Cinnamon] [Mate] [Xfce] blueman needs its own translation file for Linux Mint at Launchpad

### ISSUE THREAD

**Issue by Pjotr123** [linuxmint/mint21-beta#155]
**Describe the bug**
Blueman is now in the Mint repo for Vanessa. But it's not possible to improve its translations, as it doesn't have a translation file at https://translations.launchpad.net/linuxmint/latest/

**Comment by clefebvre** [comment]
hi @Pjotr123, Blueman is an upstream project which handles its own translations: https://github.com/blueman-project/blueman/

They use weblate.

The Mint blueman github project is just a github fork to keep up with it, prepare PR for them and host our packaging.

**Comment by Pjotr123** [comment]
@clefebvre : Thanks for the info. I've submitted a new Dutch translation there. Perhaps you can help in getting it pulled quickly, so that it can land in Vanessa as well?
https://github.com/blueman-project/blueman/pull/1800
