### ISSUE TITLE
[Cinnamon] Update the thumbnails of Adwaita's gtk-3.0 theme.

### ISSUE THREAD

**Issue by Initu-Castilhos** [linuxmint/mint21-beta#156]
Adwaita theme thumbnails are old as shown in the image below.
![Adwaita](https://user-images.githubusercontent.com/59381215/180845868-92a3b8ed-3b5e-4ad3-b743-a1a497155414.png)
![Adwaita-dark](https://user-images.githubusercontent.com/59381215/180845892-055ff7af-be66-49b7-b66d-7dcb7c6ea0e4.png)

I made the updated thumbnails as shown in the image below.

![Adwaita](https://user-images.githubusercontent.com/59381215/180846123-652806bb-1b9d-4822-921c-bc3cab4376f8.png)
![Adwaita-dark](https://user-images.githubusercontent.com/59381215/180846151-dcbc781d-3101-40d2-9d3c-6587a1df5e38.png)

To update, just download the images above.

**Comment by JosephMcc** [comment]
PR done. Thank you for providing the images.

**Comment by Acheron17** [comment]
Looks like this change wasn't picked up in the latest ISO, linuxmint-21-Cinnamon-amd64-202207261124
See image.
![Screenshot-from-2022-07-26-16-10-13c](https://user-images.githubusercontent.com/45599505/181103567-a13a5747-6ac2-4a2e-a7ea-424cb6e8947f.png)

 Files in /usr/share/cinnamon/thumbnails/gtk-3.0 still show the old image.

**Comment by JosephMcc** [comment]
That's because it hasn't actually been merged yet.
