### ISSUE TITLE
When mintUpdate is set to not run at startup, it can proclaim "Your system is up to date" even if it isn't and you've just simply not clicked 'Refresh'

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21-beta#158]
(tested on a local installation of both Cinnamon and Xfce that were fully updated on 2022-07-15 and then subsequently updated on 2022-07-25 while testing for this issue)

**Describe the bug**
When mintUpdate is set to not run at startup, if you have previously installed all updates but then haven't ran mintUpdate for a while, it can proclaim "Your system is up to date" even when your system is very much not up to date isn't and you've just simply not clicked 'Refresh'.

**To Reproduce**
1. make sure mintUpdate is disabled in Mint's startup applications
2. open mintUpdate
3. install all available updates
4. do a File -> Quit
5. wait a period of time until new updates are available (days? weeks? months?)
6. after an unknown period of time has passed, open mintUpdate
7. observe how mintUpdate proclaims that your system is up to date
8. click the "Refresh" button
9. observe how your system was _not_ actually up to date and there are in fact updates available

**Expected behavior**
If mintUpdate isn't already open in the background (e.g. on the status bar), then I would think that it would instead say something like "Press `Refresh` to check for updates" and, after the refresh, if there are no updates, _then_ it would proclaim that your system is up to date.

**Screenshots**
![animated](https://user-images.githubusercontent.com/11896003/180893150-9a11f22d-c0c7-4e11-adcc-c86cdd0f595b.png)

**Hardware and mintUpdate**
The update process also updated mintUpdate from v5.8.6 to v5.8.7

**Comment by clefebvre** [comment]
mintupdate refreshes the cache after 2 hours if I'm not mistaken. This depends on the user configuration. We need logs here to see why it doesn't do that.

**Comment by clefebvre** [comment]
yes, 10 minutes after launch and then every 2 hours after that, out of the box.

**Comment by clefebvre** [comment]
Looking at it again, this is perfectly normal.

In step 5 mintupdate is not running, so it doesn't matter how long you wait, nothing happens during that time.
In step 6 the cache is still not refreshed, so it's normal for mintupdate to think there are no updates, there aren't any in the cache.

It's configured to wait 10 minutes before it refreshes the cache after you launch it.

**Comment by NintendoManiac64** [comment]
So what do you suggest to someone like myself that doesn't like to have mintUpdate running in the background and instead prefers to manually launch mintUpdate when I want to perform updates?  Just try to remember to always hit "refresh"?

**Comment by JosephMcc** [comment]
Look in the preferences. You can set how long it takes to refresh after first opened. It's set by default to 10 minutes the first time. You can change it. If you're manually launching mintupdate just to perform the updates, I don't see why clicking refresh is that hard to remember.

**Comment by NintendoManiac64** [comment]
Does setting it to 0 minutes result it in auto-refreshing immediately when opened?  I figured that setting it to 0 was equivalent to "never".

And, I'll be honest, I already tend to forget to click "Refresh" for the synaptic package manager whenever I open it... Don't suppose that could be another thing - the ability to have that also auto-refresh when opened, especially since running it in the background isn't a thing unlike mintUpdate?

Or is this all just one of those "standard Linux-ism" that a beginner like myself just needs to learn, specifically that it's standard to not auto-refresh things like this when launching the corresponding application?
