### ISSUE TITLE
cinnamon: Increasing panel height does not increase icon spacing in taskbar

### ISSUE THREAD

**Issue by ISt4m79** [linuxmint/mint21-beta#16]
As the title says.  The slider goes up to the right (50 or even 60, Larger) but the space between the icons remains the same. In LM 20.3, changing the Panel height changes icon spacing as well. Please fix it in LM 21.

**Comment by mtwebster** [comment]
Can you provide a screenshot of the issue as well as of your settings for that panel? I can't reproduce this.

Thanks

**Comment by ISt4m79** [comment]
Yes.

![Screenshot from 2022-07-14 21-05-27](https://user-images.githubusercontent.com/109304978/179054595-4151d07d-6dbd-4b74-b7cb-1079ca8d31af.jpg)
![Screenshot from 2022-07-14 21-07-29](https://user-images.githubusercontent.com/109304978/179054602-1c20abba-094c-4a88-abc2-a4f654f92317.jpg)

**Comment by Secret-chest** [comment]
It's now configurable. Richt-click the applet.

**Comment by ISt4m79** [comment]
> It's now configurable. Richt-click the applet.

The name of the applet is "Grouped window list". Changing the distance between icons does not appear to be among the options.

**Comment by talesaraujo** [comment]
There is indeed a margin issue here. Icons are _way too close_ to each other. And as @ISt4m79 mentioned, currently there's no way to configure these margins.

Here are my screenshots (both are set up exactly the same way):

### **Linux Mint 20.3**
![lm20](https://user-images.githubusercontent.com/23703961/179375909-b17be522-554c-4e71-ad69-c3fcdac84cb9.png)

### **Linux Mint 21 BETA**
![lm21-beta](https://user-images.githubusercontent.com/23703961/179375928-44c2e31f-e2ea-4d76-bcef-3de84481ebbd.png)

### **Side-by-side**
![sxs-compare](https://user-images.githubusercontent.com/23703961/179375945-5f3100ac-c848-4a1f-86af-c9f6d6abe0e2.png)

**Comment by ISt4m79** [comment]
> There is indeed a margin issue here. Icons are _way too close_ to each other. And as @ISt4m79 mentioned, currently there's no way to configure these margins.
> 
> Here are my screenshots (both are set up exactly the same way):
> ### **Linux Mint 20.3**
> 
> ![lm20](https://user-images.githubusercontent.com/23703961/179375909-b17be522-554c-4e71-ad69-c3fcdac84cb9.png)
> ### **Linux Mint 21 BETA**
> 
> ![lm21-beta](https://user-images.githubusercontent.com/23703961/179375928-44c2e31f-e2ea-4d76-bcef-3de84481ebbd.png)
> ### **Side-by-side**
> 
> ![sxs-compare](https://user-images.githubusercontent.com/23703961/179375945-5f3100ac-c848-4a1f-86af-c9f6d6abe0e2.png)

It can be done but it's P.I.T.A. Add these two lines in your theme's cinnamon.css. Spacing 12px is how I like it, but you may experiment with other values.

![Screenshot from 2022-07-17 18-49-13](https://user-images.githubusercontent.com/109304978/179408131-34ce4fa9-1d75-498d-b431-11aadfd1ed74.png)

**Comment by JosephMcc** [comment]
There are a couple of things going on here. Spacing is now configurable in the theme. In Mint 20.3 the spacing between the icons would only increase if you set the "Colored icon size" to a specific size. I can confirm that it no longer does this in Mint21 even with that setting.

**Comment by JosephMcc** [comment]
Having played around with this. In my opinion is that the new behavior is actually the correct one. There is no reason for the spacing to grow when increasing the size of the panel. That seem like it was actually the broken behavior.
