### ISSUE TITLE
[BETA Status] Will LM 21 come with Cinnamon 5.4.9 or do you suggest jumping to the 5.5.x series to resolve remaining bugs?

### ISSUE THREAD

**Issue by ghost** [linuxmint/mint21-beta#162]
Hi developers. Since the BETA version of LM 21 was released the number of bugs has decreased significantly. Although some still exist, few can be considered critical. Which can be resolved in 5.4.9 and follow up on the rest in the 21.x series of LM. In order not to delay this release.

I appreciate you taking the time to read this, and I hope you are well. Thanks!

**Comment by JosephMcc** [comment]
Not sure I really get the point of this question, to be honest. 5.4.x versions will continue to be released as needed both during the beta and after the final release.
