### ISSUE TITLE
[Cinnamon] Choosing a custom icon, its loading forever. 

### ISSUE THREAD

**Issue by corus87** [linuxmint/mint21-beta#17]
I first noticed this when I tried to change the icon of the start menu launcher, and now the same happens when using Webapps to use a custom icon. 
It also happens when trying to change the icon of a folder. 

Those icons worked in Linux Mint 20.03 with the same file location 

![grafik](https://user-images.githubusercontent.com/25422697/179064696-2b8a1f12-0042-498b-a40f-4812cbbda75f.png)

**Comment by haggen88** [comment]
#9 related
