### ISSUE TITLE
[Cinnamon] Read comment

### ISSUE THREAD

**Issue by Secret-chest** [linuxmint/mint21-beta#18]
With the old toolbars I was able to move my mouse in the upper-right corner of the screen and click to close a maximised window, but now I can't.

**Comment by clefebvre** [comment]
I still can do so here. Using Mint-Y.

**Comment by Secret-chest** [comment]
Oh ok. I will try with my themes too. I used a stylesheet to remove padding from gtk+ toolbars, in 20.3, and minteelcome (which had an empty toolbar) couldn't be closed like that.
