### ISSUE TITLE
[Cinnamon] Can no longer set super+space as a shortcut key

### ISSUE THREAD

**Issue by korvahannu** [linuxmint/mint21-beta#19]
In Linux Mint 20.3 I used to set "Show the window selection screen" shortcut to super+space. I am no longer allowed to do that for some reason, it just shows "next group" on the shortcut row.

**Comment by mtwebster** [comment]
It sounds like maybe that shortcut has been claimed for keyboard layout switching.

Open keyboard settings, and go to the Layouts tab, then click the Options button in the lower right corner:
![image](https://user-images.githubusercontent.com/262776/179100848-2aa1d720-fe5a-416c-983c-2125a0b34b2c.png)

Once the new window opens, find 'Switching to another layout' and expand it. At the bottom see if `Win+Space` is checked - uncheck it if it is (and pick a different shortcut if you need to).

**Comment by korvahannu** [comment]
Thanks this is solved then! It really bothered me lol
