### ISSUE TITLE
Key binding issue when start menu is active and PrtScr key is pressed.

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/mint21-beta#2]
Issue in Linux Mint Cinnamon Edition:
If the start menu is activated with the mouse or super key then pressing PrtScr key does not bring up the Screenprint application.  Pressing PrtScr mutes the speaker instead.

Expected behavior:
Expected to be able to take a screen shot the same way as in Linux Mint 20.3 Cinnamon Edition.  With the start menu activated by the mouse or super key pressing the PrtScr key brings up the Screenprint application.

How to reproduce:
Activate the start menu with the mouse or super key and press the PrtScr key.
Occurs in Mint-X and Mint-Y themes.

**Comment by haggen88** [comment]
I confirm the bug, also the PrtScr key does not work when using Hot Corners {show all windows}

**Comment by mtwebster** [comment]
Fixed:
https://github.com/linuxmint/cinnamon/commit/909cfb098876a5d36290dc82df97e0c48e54efa6

**Comment by haggen88** [comment]
[mtwebster](https://github.com/mtwebster) Clicking the applets on the taskbar  [for example the calendar-sound-network] and using the PrtScr key also disables the audio

https://user-images.githubusercontent.com/68134588/179069281-ceefb905-1f73-465e-a10f-8c130deb0042.mp4

**Comment by Acheron17** [comment]
Issue has been resolved.
