### ISSUE TITLE
muffin: Lowering brightness to 0 results in a black screen

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/mint21-beta#24]
Previous versions of Cinnamon limited the minimum brightness to avoid getting a black screen.

On a macbook with Mint 21 beta, using the brightness media key to lower the brightness all the way to 0% results in a black screen.

**Comment by mtwebster** [comment]
I can reproduce with laptop shortcut keys and scrolling on the panel over the applet, but opening the power applet and dragging the bar only goes down to 1% - is this the behavior you have?

**Comment by clefebvre** [comment]
Yes same.

The limit is fine on the slider. It needs to be implemented also on the media keys and the mouse wheel. We shouldn't be able to set the brightness to 0%.
