### ISSUE TITLE
iwlwifi can't configure AX201

### ISSUE THREAD

**Issue by b0rkd0rk** [linuxmint/mint21-beta#25]
Thanks for your attention.

Based on my limited understanding of what I've read, I believe this is a known issue which should be fixable in the full release.

From within the live session:

```
neofetch | grep Kernel
                                           Kernel: 5.15.0-39-generic
```

```
lspci | grep Network
00:14.3 Network controller:Intel Corporation Wi-Fi 6 AX201 1600 MHz (rev 01)
```

```
dmesg | grep wifi
[   18.042029] iwlwifi 0000.00:14.3: enabling device (0000 -> 0002)
[   18.043161] iwlwifi: no config found for PCI dev 4df0/0000, rev=0x354, rfid=0x0
[   18.042029] iwlwifi: probe of 0000:00:14.3 failed with error -22
```

```
sudo lshw -C network
  *-network UNCLAIMED
       description: Network controller
       product: Wi-Fi 6 AX201 160MHz
       vendor: Intel Corporation
       physical id: 14.3
       bus info: pci@0000:00:14.3
       version: 01
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress msix cap_list
       configuration: latency=0
       resources: iomemory:600-5ff memory:6001124000-6001127fff
```

**edit:**  The **System Reports** utility says under **System Information** that the chip-ID for this wi-fi card is **8086:4df0**

**Comment by Acheron17** [comment]
This is an Intel firmware / Kernel issue.
Not really within the scope of the Mint distribution to resolve.  Do a deep dive web search for a solution.
Here is some info: https://askubuntu.com/questions/1377110/intel-ax201-wi-fi-6-and-ethernet-wont-work-ubuntu-20-04-and-21-10

**Comment by b0rkd0rk** [comment]
> This is an Intel firmware / Kernel issue.
> Not really within the scope of the Mint distribution to resolve.

That's unfortunate but understandable.

> Do a deep dive web search for a solution.

I had already done that before posting.  Based on what I had read, was afraid that I might end up having to compile the kernel myself in order to fix this, so I figured I'd try posting a bug report to the beta of my favorite distro to see if I could get them to fix it first.

When I read your reply, my heart sank.  But then I remembered something I'd read during my search.  I don't know exactly where this information came from, but it had something to do with the coexistence of bluetooth and wifi being poorly managed.  Maybe something to do with power.  I don't recall the details.

So I went into the system firmware/bios manager and disabled bluetooth from there.  It worked.  I got my wifi running, but of course now I don't have bluetooth.  Bluetooth wasn't really working in linux anyway.  It kept crashing.  It was the same problem with the Xubuntu 22.04 live session.

I double checked just to be sure by re-enabling bluetooth from the bios, loading mint, checking wifi, etc.  Then turning bluetooth off and loading mint again.  I did this also with Xubuntu 22.04.  Same behavior.  Wifi doesn't work unless bluetooth has been disabled in the bios.

There's definitely an issue here, but I just don't know where it is or who needs to fix it.

I will leave this open and let a project team member close it at their own discretion.

Anyway, thanks I guess...

**Comment by Acheron17** [comment]
Please try posting in the Mint Forums.  There is a much larger audience there with people like JeremyB who are pretty expert at getting WiFi to work.

**Comment by b0rkd0rk** [comment]
> Please try posting in the Mint Forums. There is a much larger audience there with people like JeremyB who are pretty expert at getting WiFi to work.

No chance of me doing that, but thank you for the suggestion.

I don't have a forum account there and I have no desire to create one.

**Comment by clefebvre** [comment]
A higher kernel series with the future EDGE ISO might help.
