### ISSUE TITLE
[Nemo] Menubar Add Bookmark don't work.

### ISSUE THREAD

**Issue by soonan5** [linuxmint/mint21-beta#29]
Just a bug. Only drag and drop to the sidebar works.
![NABM](https://user-images.githubusercontent.com/109312533/179095688-9ef4aac5-14b7-4388-a0ad-81b8c93ef29e.jpg)

**Comment by mtwebster** [comment]
I can't reproduce this - are you certain they're not being added? They get put at the very end of the 'bookmarks' section. It's easy to not notice if your window is fairly small and you have a lot of bookmarks already.
![image](https://user-images.githubusercontent.com/262776/179097834-630e538e-8bcc-4573-8bc3-fa596964acda.png)

Can you run `nemo --quit && nemo` then try to make a bookmark and see if there are any warnings? Thanks

**Comment by soonan5** [comment]
I just started a new live mode. Nothing seems to have changed.

**Comment by soonan5** [comment]
Sorry. I just started a new live mode. Nothing seems to have changed. I try `nemo --debug` but got no error.

https://user-images.githubusercontent.com/109312533/179101529-ddafd13e-56e8-48b0-9cbe-3074f301a17e.mp4

**Comment by mtwebster** [comment]
Did you mean to close this?  Is it still an issue for you?

**Comment by ghost** [comment]
Now it works. Sorry I didn't understand what caused it. Thanks for your reply.
