### ISSUE TITLE
[Cinnamon] Mint-Y-Dark Context menu border sometimes disappears.

### ISSUE THREAD

**Issue by soonan5** [linuxmint/mint21-beta#30]
It often happens when it overlaps certain colors. Green is more common.
![CM1](https://user-images.githubusercontent.com/109312533/179098128-db35f592-0e74-4857-8df9-634c9ea36f1e.jpg)
![CM2](https://user-images.githubusercontent.com/109312533/179098144-d7b95a8f-2562-477e-a786-f5b677e89b4f.jpg)

**Comment by JosephMcc** [comment]
I don't think it's disappearing. I think it's just the contrast between the two colors causing that visual. There is nothing that can really make it actually disappear.
