### ISSUE TITLE
[Cinnamon] wmctrl no longer pre-installed

### ISSUE THREAD

**Issue by PicoMitchell** [linuxmint/mint21-beta#31]
On previous versions of Linux Mint, the `wmctrl` command has been pre-installed, but that no longer appears to be the case.

Is that an an intentional change or a bug?

**Comment by Acheron17** [comment]
I am fairly certain that is not necessary any longer since Linux Mint 21 no longer uses metacity.

**Comment by PicoMitchell** [comment]
But Mint 21 still uses X11 (Xorg) and not Wayland, regardless of Metacity vs Mutter being used.

`wmctrl` works with X11 and still works fine on Mint 21 when it's manually installed.

Maybe it got removed on the Ubuntu 22 side of things because they switched to defaulting to Wayland? But, it's still useful and valuable on Mint 21 with X11.

**Comment by mtwebster** [comment]
Metacity is still used for cinnamon's fallback mode. Regardless, it does look as though it was dropped from Ubuntu, which would explain this.

**Comment by mtwebster** [comment]
I just noticed blueberry used to depend on wmctrl and we no longer use it. This probably explains why it's not on the iso.

**Comment by PicoMitchell** [comment]
Ah interesting. Well, I hope it can get re-added. I've got use cases where a script running as the user (not as root) need to be able to detect if specific window names are open as well as close and activate windows.

Requiring needing to install `wmctrl` manually would require running as root which would not be ideal for a script running as the user.

Or does there happen to be some other window manager tool pre-installed that I'm not aware of? Wouldn't be against switching if that's the case.

**Comment by clefebvre** [comment]
Added to the list for the next ISO.

**Comment by PicoMitchell** [comment]
Thank you!
