### ISSUE TITLE
[XFCE] Entire bottom panel disappears when removing a panel launcher

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21-beta#33]
Easiest way to replicate this issue is:

1. boot the live ISO for XFCE

2. on the bottom panel near the left corner, right-click on either Firefox or Thunar and then click "Remove" (and then click "Remove" in the dialog window that appears)

3. ...and your entire bottom panel has now disappeared

Interestingly, this does not occur if you instead did a right-click -> "Remove" on the 'Show Desktop' or 'Terminal' panel launchers and, at least with the default configuration, only occurs with Firefox and Thunar.  That being said, you can get it to occur with newly-added panels launchers as well via something like the following:

1. boot the live ISO for XFCE

2. in the applications menu, look for Thunderbird, right-click on it, and select "Add to Panel"

3. right click on the newly-added panel launcher for Thunderbird located on the farthest right and select "Remove" (and then click "Remove" in the dialog window that appears)

3. ...and your entire bottom panel has now disappeared

**Comment by hugok79** [comment]
I also confirm this bug.
Thanks @b0rkd0rk for the workaround info

**Comment by smurphos** [comment]
Probably this - https://gitlab.xfce.org/xfce/xfce4-panel/-/issues/533

**Comment by JosephMcc** [comment]
This is the same issue as this one: https://github.com/linuxmint/mint21-beta/issues/65

**Comment by NintendoManiac64** [comment]
Bu-but... mine was reported 2 days before #65 :(

(it doesn't really bother me but it was my impression that usually it's the bug that was filed first that gets kept?)
