### ISSUE TITLE
Audacity (flatpak) hangs when opened

### ISSUE THREAD

**Issue by ovari** [linuxmint/mint21-beta#38]

**Comment by mtwebster** [comment]
I'm not sure this is Mint related, a quick search turns up reports of the same problem on other distributions. Maybe an issue with pipewire.

https://www.reddit.com/r/pop_os/comments/va39wa/audacity_doesnt_openrun_after_systempipewire/

**Comment by ovari** [comment]
Thank you for the link @mtwebster.

>Today System76 updated pipewire to v0.3.53 on my rig. Now the problem seems to be finally solved, as Audacity opens with ALSA and JACK just as fine as before the "nightmare" described in this thread, no more freezes.
>
>Thank you, System76!!!

https://www.reddit.com/r/pop_os/comments/va39wa/comment/if42cnp/

Does Linux Mint 21 have pipewire v0.3.53?

Thank you

**Comment by JosephMcc** [comment]
Mint has v0.3.48 from Ubuntu.

**Comment by ovari** [comment]
Does an issue need to be created at Ubuntu? If so, how can this be done? Thank you

**Comment by clefebvre** [comment]
Since it's flatpak I'd start by looking for a similar issue and eventually reporting directly at Audacity at https://bugzilla.audacityteam.org/.

**Comment by ovari** [comment]
> Since it's flatpak I'd start by looking for a similar issue

Hopefully the issue is https://github.com/flathub/org.audacityteam.Audacity/issues/90#issuecomment-1192982078
