### ISSUE TITLE
[XFCE] Default 'backdrops' folder no longer listed if you change background to a different folder and then log out

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21-beta#39]
1. boot the live ISO for XFCE

2. set the desktop background to a file that is located in a different folder (that being _not_ in the default 'backdrops' folder)

3. log out and then log back in

4. now when you open the "Desktop Settings..." select the "Folder" drop-down on the "background" tab, you'll notice that the default 'backdrops' folder will now be completely missing from the list

**Comment by clefebvre** [comment]
Confirmed. You're good at finding paper cuts! :)

This is a feature which should be requested in Xfce. I think this is part of xfdesktop: https://gitlab.xfce.org/xfce/xfdesktop/-/issues

The default selected path is /usr/share/xfce4/backdrops, they could add it as an extra choice in the combo box.
