### ISSUE TITLE
[XFCE] Shift+Insert does not paste copied files

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21-beta#41]
1. boot the live ISO for XFCE

2. locate any file or folder you want to copy and copy it in some manner (e.g. via right-click)

3. go to the folder you want to paste it to and press Shift+Insert

4. ...nothing will happen

5. however, if you now open the "Text Editior" (xed) and do a Shift+Insert, it will actually paste the location of the copied file

I suppose it's theoretically possible that this is an intentional design choice?  I mean, it seems that Ctrl+Insert also does not copy files yet works for copying text, but it's step 5 that has me questioning that this might actually be a bug since, if you do a Ctrl+v for step 5 instead, you will end up with the exact same result

**EDIT**: Cinnamon generally seems to behave the same way except that it'll show the pasted text on step 4 in a temporarily sort of text-entry box, but still nothing happens

**Comment by clefebvre** [comment]
Copying/pasting files with Ctrl-C, Ctrl-V works as expected. Nothing indicates Shift+insert is supported by Thunar. This can be requested as a feature request on the Xfce/thunar gitlab.
