### ISSUE TITLE
xfce: power manager applet icon looks like a battery indicator

### ISSUE THREAD

**Issue by n-buna404** [linuxmint/mint21-beta#42]
Battery icon shows charging with battery when plugged in even though laptop is without battery. This differs from mint 20.3.

**Comment by clefebvre** [comment]
Please provide a screenshot and the output of:

`upower -d`

**Comment by n-buna404** [comment]
Device: /org/freedesktop/UPower/devices/line_power_AC
  native-path:          AC
  power supply:         yes
  updated:              Fri 22 Jul 2022 08:29:00 PM +08 (293 seconds ago)
  has history:          no
  has statistics:       no
  line-power
    warning-level:       none
    online:              yes
    icon-name:          'ac-adapter-symbolic'

Device: /org/freedesktop/UPower/devices/DisplayDevice
  power supply:         no
  updated:              Fri 22 Jul 2022 08:29:00 PM +08 (293 seconds ago)
  has history:          no
  has statistics:       no
  unknown
    warning-level:       none
    percentage:          0%
    icon-name:          ''

Daemon:
  daemon-version:  0.99.17
  on-battery:      no
  lid-is-closed:   no
  lid-is-present:  yes
  critical-action: HybridSleep
![Screenshot_2022-07-22_20-31-10](https://user-images.githubusercontent.com/68980945/180440144-bdaa8319-1b01-48ea-a309-18689fb5630a.png)

**Comment by clefebvre** [comment]
Thanks @n-buna404.

Is the upower output different in 20.3?

Although there's no power percentage in your upower output here, there is a battery output, so it seems normal Xfce shows it.

I'm trying to see what changed between 20.3 and 21... whether this is the result of a change in upower, or in xfce.

**Comment by n-buna404** [comment]
You are welcome.
Yup, they differ slightly. There is no percentage in the old upower output for 20.3. (This is from live boot since i overwrite old partition.)
Device: /org/freedesktop/UPower/devices/line_power_AC
  native-path:          AC
  power supply:         yes
  updated:              Fri Jul 22 14:19:34 2022 (43 seconds ago)
  has history:          no
  has statistics:       no
  line-power
    warning-level:       none
    online:              yes
    icon-name:          'ac-adapter-symbolic'

Device: /org/freedesktop/UPower/devices/DisplayDevice
  power supply:         no
  updated:              Fri Jul 22 14:19:34 2022 (43 seconds ago)
  has history:          no
  has statistics:       no
  unknown
    warning-level:       none
    icon-name:          'battery-missing-symbolic'

Daemon:
  daemon-version:  0.99.11
  on-battery:      no
  lid-is-closed:   no
  lid-is-present:  yes
  critical-action: PowerOff
![Screenshot_2022-07-22_14-21-08](https://user-images.githubusercontent.com/68980945/180460439-fae6b65e-3ac9-4351-a452-ae7180fdf058.png)

**Comment by clefebvre** [comment]
The output looks the same to me... and checking the versions of xfce4-power-manager, they're the same as well.. both 4.16.0-1 in 20.3 and 21..

**Comment by clefebvre** [comment]
ah wait, I know what's going on...

![image](https://user-images.githubusercontent.com/1138515/180602335-07eb5fba-c9f9-4c26-bfbf-663cc3b11bd4.png)

I can reproduce it in Virtualbox. It's nothing to do with your hardware. This is 20.3 on the left, 21 on the right. The icon changed, that's all. This isn't actually a battery indicator, it's the icon used by the Xfce power manager.

**Comment by n-buna404** [comment]
Sorry I do not get what u meant. Is 'battery missing symbolic' icon missing after the icon changes? The comparison picture shown to me is just icon changes indicating charging . The symbols change to me is not the problem. But it supposed to show like in red circle when u plugged laptop in but without battery
![180460439-fae6b65e-3ac9-4351-a452-ae7180fdf058](https://user-images.githubusercontent.com/68980945/180604037-0475922f-d414-4853-9d00-d038eb507e3d.png)

**Comment by clefebvre** [comment]
No, I mean, the icon shows even if there's no battery. It's a design limitation in Xfce Power Manager applet.

**Comment by n-buna404** [comment]
But that was not the case for 20.3. It will show "battery missing symbolic"
on my device.

**Comment by clefebvre** [comment]
It shouldn't even do that. The battery-missing-symbolic is for your Display device. I have the same here in my virtualbox upower output.

Ideally it should show no icon at all. If you don't have a battery then this applet isn't useful to you, you can just right-click it and remove it from the panel.

**Comment by n-buna404** [comment]
Yup it made sense that I do not need the icon to show battery level. I am just reporting this since the icon changes from 20.3 to 21 can be misleading to some extent. To me the ideal behavior will be there will be 3 type of icon one for with battery& plugged in, only battery and only plugged in (just like 20.3 but based your feedback, it was working only for certain devices)

Furthermore, the icon is useful for changing screen brightness, switching to presentation mode and opening power manager. I personally prefers to keep it.

**Comment by clefebvre** [comment]
The decision was made to have it there rather than to remove it in earlier releases, so I agree with you. I'll try to chase why the icon changed.. after looking at the code and the icon theme, this isn't clear to me yet.

**Comment by clefebvre** [comment]
Fixed.
