### ISSUE TITLE
ZFS on Linux Encrypted Root Pool

### ISSUE THREAD

**Issue by StealthyBigGenius** [linuxmint/mint21-beta#43]
The installer for Ubuntu v22.04 LTS (Jammy Jellyfish) includes a feature to install to a ZFS on Linux rpool (root pool) using native encryption.

The installer for Linux Mint v21.0 BETA (Vanessa), Cinnamon, 64-bit does not include the same feature to install to ZFS at all--encrypted or not.

Using the Linux Mint v21.0 BETA, Cinnamon, 64-bit DVD, boot into the live environment.

Start a Terminal, and enter the following commands to install the missing ZFS components:
sudo apt-get update
sudo apt-get install zfsutils-linux zfs-initramfs zfs-zed

From the desktop, double-click "Install Linux Mint".

From "Erase disk and install Linux Mint", click button "Advanced features...".

Select option "Erase disk and use ZFS".

Check the checkbox for "Encrypt the new Linux Mint installation for security".

Click button "OK".

Continue installing as normal.

NOTE:  The aforementioned process was tested on a Linux Mint v19.1 QEMU-KVM host with a guest of Linux Mint v21.0 BETA, Cinnamon, 64-bit running with the default i440FX chipset.

Can the missing ZFS components be added to Linux Mint so that Ubiquity can more easily install to ZFS?

Thank you!

**Comment by clefebvre** [comment]
Thanks, these packages will be added.
