### ISSUE TITLE
ubiquity: post-install, files are left in /var/cache/apt/archives

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/mint21-beta#5]
Issue:
At the end of the installation apt clear is not issued.

Expected behavior:
User should be left with an empty apt cache after a fresh install.

How to reproduce:
After Linux Mint installation completes and reboots check /var/cache/apt/archives.  The LMDE 5 installer clears the apt cache.

**Comment by clefebvre** [comment]
Added to roadmap for consideration in 21.1
