### ISSUE TITLE
[Cinnamon] Problems during Cinnamon startup XApp Status applet

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/mint21-beta#50]
After applying all of today's fixes rebooted and saw this notification.  Had never seen it before.
![image](https://user-images.githubusercontent.com/45599505/179247083-0aefd815-4905-4b6e-bd6b-e41b97ef451c.png)
Here is the xsession-errors log: https://termbin.com/q5sj
Also seeing this contradictory message from the System Reports, see the screen shot.
![image](https://user-images.githubusercontent.com/45599505/179247742-e8424984-8313-4c9a-8637-bfdc7d5a7b19.png)

This issue won't go away, it is solid repeatable now.

**Comment by mtwebster** [comment]
Oops - new version incoming.

https://github.com/linuxmint/cinnamon/commit/c41791b526fa792405f404c3fa57d2dd3ab8a565

**Comment by spamegg1** [comment]
I had the exact same issue after the updates. This might be relevant:
![Screenshot from 2022-07-15 18-22-04](https://user-images.githubusercontent.com/4255997/179254617-1b3d02d6-8191-41cd-8acb-c08eb3109d0e.png)
![Screenshot from 2022-07-15 18-22-28](https://user-images.githubusercontent.com/4255997/179254635-b6e9835e-09f7-428c-aff8-10ac1083a8d9.png)

**Comment by mtwebster** [comment]
Check the update manager for cinnamon 5.4.4, should be fixed

**Comment by spamegg1** [comment]
Can confirm 5.4.4 fixed the issue.

**Comment by Harry-W-Haines-III** [comment]
Sorry, had to reload my system.  Melange sows no errors.  All is good visually.
