### ISSUE TITLE
[CINAMMON] screen flashes, impossible to use it.

### ISSUE THREAD

**Issue by Pierred17** [linuxmint/mint21-beta#52]
Must install in recovery mode. It doesn't work in standard mode. 
Laptop : Clevo N7x0WU with Intel CPU and Intel UHD Graphics 620 GPU.
The screen flashes, it is impossible to use it. 
Bug happens always.
Works correctly on Linux Mint 20.3
nomodeset option doesn't work

**Comment by Pierred17** [comment]
Kernel 5.15 doesn't work with  Intel UHD Graphics xxx GPU.
A lot of ubuntu 22.04 user are concerned
Must use kernel before 5.15 or since 5.18

**Comment by clefebvre** [comment]
Hi,

We can't help much with this unfortunately. The solution will come in the form of an EDGE ISO which will feature a higher kernel series.
