### ISSUE TITLE
celluloid: Hardware-accelerated video decoding appears broken

### ISSUE THREAD

**Issue by GrantSheehan** [linuxmint/mint21-beta#54]
On an Optimus-enabled laptop (AMD 6900HX + stock Mesa, NVIDIA 3070ti + 510 proprietary drivers), watching videos with hardware accelerated decoding shows stuttering initially and then the system goes unresponsive when viewed with both in VLC and Celluloid. I tried switching to both AMD-only and NVIDIA-only graphics drivers to see if it affected one but not the other and I see similar behavior in both instances. Once I disabled hardware-accelerated decoding in VLC, videos played without discernable issue.

In the interest of reproducibility and avoiding licensing headaches, [here's](https://archive.org/details/BigBuckBunny_328) a a CC-licensed video that exhibits the behavior I'm describing (the 512KB MP4 downloaded version).

**Comment by spamegg1** [comment]
I had the same stuttering issue in Celluloid with pretty much any video file I tried.

Under `Preferences/Miscellaneous/Extra mpv options` I changed the `hwdec=yes` parameter to `hwdec=auto-copy` and the stuttering is gone. (Alternatively `hwdec=vaapi-copy` also works.)

**Comment by clefebvre** [comment]
I couldn't find the source of the regression. This is however upstream from us, none of the components at play here are developed by Linux Mint. If you find the cause of the issue and there's a known fix we can apply please reopen a new issue.
