### ISSUE TITLE
[GRUB] USB boot menu not themed

### ISSUE THREAD

**Issue by PicoMitchell** [linuxmint/mint21-beta#55]
This appears to be a regression from Mint 19.3 where the `/boot/grub/grub.cfg` file started with the following code and properly themed the USB GRUB menu:
```
if loadfont /boot/grub/font.pf2 ; then
	set gfxmode=auto
	insmod efi_gop
	insmod efi_uga
	insmod gfxterm
	terminal_output gfxterm
	set theme=/boot/grub/themes/linuxmint/theme.txt
fi
```

Then, in Mint 20 through Mint 20.3 the USB GRUB menu was changed to only specify the following code without setting the theme, even though all of the theme resources still exist and could be displayed properly when the final line was added manually:
```
if loadfont /boot/grub/font.pf2 ; then
	set gfxmode=auto
	insmod efi_gop
	insmod efi_uga
	insmod gfxterm
	terminal_output gfxterm
fi
```

Now, in Mint 21, the grub.cfg file only starts with `loadfont unicode` without any of the other configurations set, but the theme resources still appear to exist at `/boot/grub/themes/linuxmint/theme.txt` and presumably could still be used. The previous `/boot/grub/font.pf2` font has been removed, but I'm assuming for unicode font at `/boot/grub/fonts/unicode.pf2` could be used instead with the theme.

Is it an intentional change to not theme the GRUB menu while the BIOS ISOLINUX menu is still themed? Or is this a bug/oversight?

**Comment by PicoMitchell** [comment]
I've confirmed that the following code still works fine to theme GRUB on a Mint 21 USB:

```
if loadfont unicode; then
	set gfxmode=auto
	insmod efi_gop
	insmod efi_uga
	insmod gfxterm
	terminal_output gfxterm
	set theme=/boot/grub/themes/linuxmint/theme.txt
fi
```

**Comment by clefebvre** [comment]
Hi,

The theme was removed for compatibility reasons. We found during 20 BETA that it caused the ISO to be unable to boot on some hardware specs. A section was added to the user guide to theme it post-install.
