### ISSUE TITLE
Wired network not automatically reconnected to an OpenWRT router that has no internet connection if you unplug ethernet, wait for the "disconnected" message, then re-plug ethernet

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21-beta#60]
(was tested on Cinnamon & XFCE)

When connected via ethernet to an OpenWRT router that has no internet connection, if you unplug your PC's ethernet cable, wait a bit, then plug the ethernet back in, Mint does not automatically reconnect to the local network and you must manually select it through the GUI.

1. have an OpenWRT router powered on but disconnected from the internet

2. connect an ethernet cable from one of the LAN ports on your OpenWRT router to your PC

3. boot a live session of the Mint 21 beta ISO on your PC

4. open Firefox and navigate to your router's default gateway (commonly 192.168.1.1) to confirm that you have a working network connection

5. unplug the ethernet cable from your PC

6. wait a bit until the "disconnected" message pops up in the top-right of your screen

7. reconnect the ethernet cable to your PC that has no wifi or has wifi disabled

8. notice that no "connected" message appears in the top-right; you can similarly try to navigate to your router via Firefox and you'll notice that you should indeed have no network connection

From there if you click on the network icon in the right side of the bottom panel, you'll notice that "wired connection" will be listed under 'Available' at which point, if you click it, _then_ you will have a wired connection.

...that being said, I was able to similarly have the same issue occur even when I had an internet connection via the following process instead using the combination of an OpenWRT router and a non-OpenWRT DSL modem:

1. have an OpenWRT router powered on and connected to the internet though an ethernet cable into a DSL modem that uses a default gateway of 192.168.254.254 (a cable modem may also work)

2. connect an ethernet cable from one of the LAN ports on your OpenWRT router to your PC

3. boot a live session of the Mint 21 beta ISO on your PC that has no wifi or has wifi disabled

4. open Firefox and confirm that you have a working internet connection

5. unplug the ethernet cable from your PC

6. wait a bit until the "disconnected" message pops up in the top-right of your screen

7. connect your PC that has no wifi or wifi disabled directly to your DSL (or cable?) modem via ethernet

8. notice that no "connected" message appears in the top-right; you can similarly try to navigate to a website via Firefox and you'll notice that you should indeed have no network connection

And, once again, if you click on the network icon in the right side of the bottom panel, you'll notice that "wired connection" will be listed under 'Available' at which point, if you click it, _then_ you will have a wired connection.

Normally one would think that this is an OpenWRT bug but it doesn't happen with Mint 18.3 nor Windows 7, yet it also doesn't happen even with Mint 21 beta if I use a 17(?) year-old NETGEAR WGR614v6 router that doesn't have OpenWRT nor does it happen if I only connect to my OpenWRT router when it does have an internet connection or connect only to my DSL modem regardless of whether it has an internet connection or not. Furthermore, the issue occurred in the second scenario only when unplugging from the OpenWRT router but connecting to my non-OpenWRT DSL model.

This also occurred with two different OpenWRT routers - a NETGEAR WPN824N with an Atheros AR7240 rev 2 chipset as well as a NETGEAR N600 WNDR3400v1 with a brcm47xx Broadcom chipset.  Also the DSL modem is an Actiontec T3200 provided by the Windstream ISP.

(I also tried two different methods to even restore the factory, non-OpenWRT firmware on my N600 router but I was unsuccessful...)

And to be clear, expected behavior would be to simply have it reconnect to the wired network automatically.

For reference, the PC hardware that this was tested with was a Thinkpad T420 (with a Sandy Bridge i5 + Intel integrated graphisc), an Acer Extensa 5620Z (with a Core 2 Duo T8300 + Intel 965GMA graphics), an Acer Aspire 5315-2639 (with a Core 2 Duo T5800 + Intel 965GMA graphics), and a custom desktop with a Phenom II + Asus M4A78T-E + integrated AMD HD3200 graphics + some 100mbps Linksys PCI non-express ethernet card (because the motherboard's internal ethernet, while 1Gbps down, is only 10Mbps up - not a typo).

**Comment by clefebvre** [comment]
Hi,

This is either an issue with the router or with network-manager. Both Xfce and Cinnamon just provide frontends to network-manager and delegate all networking to it.

In Cinnamon, to help troubleshooting, you can actually remove the network applet. This will result in the network-manager applet showing up in the tray.

If this is a bug it should be reported to network-manager directly.
