### ISSUE TITLE
Reported battery percentage increases by 1% when unplugging the charger when battery is below 100%

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21-beta#61]
(tested on both Cinnamon and XFCE)

Simply put, if your battery is below 100%, then the reported battery percentage will increase by 1% when you disconnect the charger.

1. boot the live ISO for Mint 21 beta

2. make sure your laptop or tablet has a battery charge level below 100%

3. have the battery charge for a bit (a minute? 5 minutes? it might not even matter)

4. unplug the charger

5. the moment that Mint displays that you are now discharging, your battery percentage will be 1% higher than it was just before you unplugged the charger

The expected behavior would be for the percentage to remain the same or to actually have decreased a teeny bit.

The hardware used for this test was a Thinkpad T420 (with a Sandy Bridge i5 + Intel integrated graphics) as well as a OneXPlayer "gaming" tablet (with a Ryzen 4800U + AMD integrated graphics).

**Comment by clefebvre** [comment]
Is that a Cinnamon bug or a upower one?

Can you reproduce the issue with:

`upower -d`

**Comment by clefebvre** [comment]
Ah sorry, I just noticed this also happened in Xfce. It's definitely upstream from us then and should be reported upstream directly.
