### ISSUE TITLE
[Xfce] Locking the user session cuts off network traffic after about 1 minute

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21-beta#62]
(this was tested on both Cinnamon and XFCE, but the bug only occurs on XFCE and _not_ on Cinnamon)

Simply put, if you lock the current user session (whether manually and/or letting it time out on its own), then any network traffic will be cut off after about 1 minute.

**To Reproduce**
1. boot into Mint 21 Xfce BETA (you can use either a fully-updated local installation or the live ISO, but note that the live ISO requires an additional step due to bug a separate bug)

2. launch the software manager, then search for and install gnome-system-monitor

3. open the Gnome "System Monitor" and set it to the "resources" tab, keeping an eye on the "Network History"

4. [LIVE SESSION ONLY; skip this step if using a local installation] Due to bug #64, you must log out of the current user session and then log back in; once logged back in, re-launch the Gnome "System monitor" and make sure it's on the "resources" tab

5. ideally on a slow internet connection, open Firefox and download any large file (Mint's own ISOs can work; Manjaro's downloads are an additional GB larger if your internet is too fast)

6. lock the current user session

7. after about a minute or more, unlock the session

8. if you look at the GNOME system monitor, you should see that network activity had completely stopped and, depending on the server that you were downloading from, your download may even have straight-up failed (I found this to be the case with at least the "US Internet" Linux Mint mirror)

**Expected behavior**
Like on Cinnamon, network activity should not be cut off when the session is locked.

This was tested on a Thinkpad T420 (with a Sandy Bridge i5 + Intel integrated graphics) with both ethernet and wifi as well as on a OneXPlayer "gaming" tablet (with a Ryzen 4800U + AMD integrated graphics) albeit the latter only on ethernet.

I also found that, if you're loading particularly javascript-heavy webpages, then webpage rendering itself can even stop when the session is locked (but this might just be due to the network connection being cut off and the heavy javascript relying on the aforementioned network connection in some manner).

**Comment by clefebvre** [comment]
Unfortunately I think that's a limitation of light-locker. The fact that the VT is switched and the DM is effectively performing as a greeter for the screensaver means we lose access to the session. This has other effects such as a the loss of sound.. say you're a DJ, you want to lock your screen without stopping the music.. 

We're planning on moving towards xfce4-screensaver but it won't happen in 21.
