### ISSUE TITLE
xfce: light-locker terminates randomly in live-session

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21-beta#64]
(this was tested on both Cinnamon and Xfce, but this bug only occurs on Xfce and not Cinnamon)

**Describe the bug**
With a working internet connection, you cannot lock the current user in live session if you had previously viewed the software manager after it had finished generating its cache and/or if you had opened the program Gnome "System Monitor"

**To Reproduce**
1. boot the Xfce live ISO
2. be connected to the internet (wifi or ethernet)
3. lock the current user session to confirm that it in fact works
4. log back in, then open the Software Manager
4-bonus. [optional] you can actually successfully lock the current user session if you do it in the middle of the "Generating cache" process
5. wait for it to finish generating cache
6. try to lock the current user session... instead, nothing will happen even if you close the Software Manager

From there, log out of the current session and log back in, at which point you will be able to lock the current user without issue.  However...

7. without rebooting your PC, open the Software Manager and search for "gnome system monitor"
8. download and install the "gnome-system-monitor" program, but do NOT launch it
9. once the download and installation is finished, close the Software Manager
10. lock the current user session to confirm that it in fact works
11. log back in, then open "System Monitor"
12. try to lock the current user session... instead, nothing will happen even if you close the Gnome "System Monitor"

Interestingly, if you disconnect from the network before doing step 11 and _then_ open "System Monitor", you'll be able to lock the current user session without issue

**Expected behavior**
One should be able to lock the current session regardless of if you opened and then closed a specific program.

For reference, this was tested on a Thinkpad T420 (with a Sandy Bridge i5 + Intel integrated graphics) on both ethernet and wifi.

**UPDATE**: Just discovered that this issue also occurs with the "Appearance" settings application; e.g. directly after booting a live session, if you open "Appearance", you will no longer be able to lock the current user session until you log out.

**Comment by NintendoManiac64** [comment]
Just discovered that this issue also occurs with the "Appearance" settings application; e.g. directly after booting a live session, if you open "Appearance", you will no longer be able to lock the current user session until you log out.

**Comment by clefebvre** [comment]
It looks like running mintinstall and waiting for the cache to generate just terminates light-locker somehow. It feels like an issue with light-locker. I'm not considering it a blocker though:

- I made sure it only affected the live session.
- We're planning to move towards xfce4-screensaver in replacement of light-locker already, this is already in the roadmap.
