### ISSUE TITLE
xfce4-panel: Removing thunar launcher crashes the panel

### ISSUE THREAD

**Issue by clatterfordslim** [linuxmint/mint21-beta#65]
Only happens during ISO install, but has been in the XFCE Edition since Ulyssa 20.1. It has now come over to Vanessa.
When right click remove Thunar off of panel, it removes the panel. It continuously got worse in Uma and Una. Whilst adding apps to panel the wrong app would go up, using Panel-Launcher from Whisker Menu. It would start with Firefox, Terminal, then Thunar. After trying to add App a fourth time it would add it correctly. Removing either Firefox or Thunar off of Panel will cause panel to be removed.

**Comment by JosephMcc** [comment]
From what I read on the Mint forums this is a bug in XFCE which it seems maybe is fixed in 4.16.4 which is not currently available in the repos.

**Comment by smurphos** [comment]
> From what I read on the Mint forums this is a bug in XFCE which it seems maybe is fixed in 4.16.4 which is not currently available in the repos.

4.16.4 is tagged for release upstream - don't Mint package xfce-panel in upstream anymore?

**Comment by JosephMcc** [comment]
I'm unsure about that. I think it just depends on weather or not it's needed. That's honestly outside of what I personally work on.

**Comment by clatterfordslim** [comment]
I added this to the beta and the disappearing panels has stopped for good. Upgrading to 4.16.4
sudo add-apt-repository ppa:xubuntu-dev/staging
sudo apt update
sudo apt full-upgrade

**Comment by NintendoManiac64** [comment]
I'm re-posting my content here since my #33 was closed as being a duplicate (even though mine was posted 2 days earlier? It doesn't bother me; I just find it odd....)

> Easiest way to replicate this issue is:
> 
>     1. boot the live ISO for XFCE
> 
>     2. on the bottom panel near the left corner, right-click on either Firefox or Thunar and then click "Remove" (and then click "Remove" in the dialog window that appears)
> 
>     3. ...and your entire bottom panel has now disappeared
> 
> 
> Interestingly, this does not occur if you instead did a right-click -> "Remove" on the 'Show Desktop' or 'Terminal' panel launchers and, at least with the default configuration, only occurs with Firefox and Thunar. That being said, you can get it to occur with newly-added panels launchers as well via something like the following:
> 
>     1. boot the live ISO for XFCE
> 
>     2. in the applications menu, look for Thunderbird, right-click on it, and select "Add to Panel"
> 
>     3. right click on the newly-added panel launcher for Thunderbird located on the farthest right and select "Remove" (and then click "Remove" in the dialog window that appears)
> 
>     4. ...and your entire bottom panel has now disappeared

**Comment by clatterfordslim** [comment]
Upgrading to 4.16.4 in Uma and Una has stopped the disappearing panels, as well as in Vanessa Beta.

**Comment by clatterfordslim** [comment]
Found whilst adding Thunar back to panel, that if you keep on adding Thunar, it goes through from Thunar, then it puts Firefox up from Thunar Right Click in Whiskermenu add to panel, then adding Thunar again it adds Xfce-Terminal. After adding Terminal from Thunar app right click in Whiskermenu add to panel, carried on adding just Thunar. I deleted all icons off of panel, logged out added Thunar to panel, then Thunar again, which resulted in adding Firefox to panel, added Thunar again which yes you guessed correctly added Terminal from Thunar App. I will go back to 4.16.3 and see if it is doing the same in there? If it is, then at least we know that upgrading to 4.16.4 disables the panel disappearing or being deleted. This Thunar thing has me stumped.

**Comment by clefebvre** [comment]
Upgrading xfce4-panel to 4.16.4 (along with its lib pkg) fixes the issue.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mint21-beta/issues/131 is not fixed in xfce4-panel 4.16.4, it continues to happen.

**Comment by clefebvre** [comment]
xfce4-panel 4.16.4 added to vanessa.
