### ISSUE TITLE
mate: wrong date format with occitan

### ISSUE THREAD

**Issue by Mejans** [linuxmint/mint21-beta#66]
**Describe the bug**
I tried the Mate variant and noticed that the date format is not right.
This is for Occitan locale, the quote between the h shouldn't appear on screen.
I don't know where to change that.

Made a post on the forum where I put a picture: https://forums.linuxmint.com/viewtopic.php?f=43&t=377484

**To Reproduce**
Use the beta version with the Occitan locale selected.

**Expected behavior**
The date format should be: day name in short day number without initial 0 month name in short hour+h+minute
**Screenshots**
On the forum post

**Comment by clefebvre** [comment]
![image](https://user-images.githubusercontent.com/1138515/180188722-eb369852-f8f4-4197-bb46-9b189ed75205.png)

**Comment by clefebvre** [comment]
OK, it's definitely using the locale's format but that format seems to be wrong then....

You can confirm that this is a system issue and not a MATE issue by showing the date in the terminal:

![image](https://user-images.githubusercontent.com/1138515/180189169-c9ea11a9-5877-4dd1-8195-94711e41a7d8.png)

**Comment by clefebvre** [comment]
Can you reproduce the issue in Cinnamon?

**Comment by Mejans** [comment]
Hello,
no, with Cinnamon it's perfect. I don't where to look at to find the string that format the date there for MATE.
![VirtualBox_Linux mintCinna_23_07_2022_13_30_46](https://user-images.githubusercontent.com/61360811/180603411-46bb8dbd-5cf1-4cda-bf44-97e650a15d40.png)

**Comment by clefebvre** [comment]
Thanks @Mejans this confirms it's a MATE issue and not an issue with the locale defaults in Debian then. Please report this upstream to the MATE project.

https://github.com/mate-desktop/mate-panel/issues

**Comment by Mejans** [comment]
Found it in MATE :)
Désolé du dérangement @clefebvre
