### ISSUE TITLE
[Cinnamon] Pin to panel adds new panel launchers instead of adding to GWL

### ISSUE THREAD

**Issue by bwepstein** [linuxmint/mint21-beta#76]
Cinnamon
Panel Icons
When clicking on add to panel, icon adds to tray of panel not the left side.
Happens for adding all icons.
Cannot change position or drag to left side.

**Comment by JosephMcc** [comment]
Edited to fix the title

**Comment by mtwebster** [comment]
duplicate of https://github.com/linuxmint/mint21-beta/issues/71 (fixed)

**Comment by bwepstein** [comment]
Still not working. checked for all updates.
