### ISSUE TITLE
Mouse cursor graphics is misaligned by 1 pixel vertically and 1 pixel horizontally

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21-beta#82]
(this was tested on Cinnamon and Xfce whether live sessions or fully-updated local installations; as a sanity-check to confirm that xorg is not the source of the bug, I've also confirmed that it occurs in a live session of Fedora 36 running straight wayland [this process described on stack exchange](https://unix.stackexchange.com/a/325972) and also by confirming that the `xrandr` command didn't work on Fedora 36, farther evidence that xorg wasn't active)

**Describe the bug**
The mouse cursor graphic itself seems to be misaligned by 1 pixel horizontally and 1 pixel vertically. In other words, where the OS itself thinks the mouse cursor is located is not the upper left-most point of the cursor graphic aka pixel coordinates of x=1,y=1 but rather pixel coordinates of x=2,y=2

**To Reproduce**
Move your mouse cursor to the edge of the screen, the corners of the screen, etc.  It's most noticeable if you run at a low resolution (e.g. 800x600) and use a white-outlined black cursor.

If you put your cursor in the top-left corner, the top row and left row of pixels on the cursor gets completely cut off yet, if you put your cursor on the bottom-right corner, 2x2 pixels will still be visible. Similarly, if you move the cursor to the middle of the right edge of the screen, 2 vertical rows of pixels will be visible.

Also, when you put the mouse cursor in the very top-left corner or the very top-right corner and do a left click-and-hold to make a selection rectangle, you can see that the selection rectangle will in fact go to the very edges and corners of the screen, suggesting that it really is just the cursor graphic that is misaligned rather than the actual physical location of your mouse.

It's important to note however that, if your run a Windows guest inside VirtualBox (windowed or fullscreen) from a Linux host, this cursor misalignment does not occur inside the Windows guest but immediately does occur as soon as you move your cursor out of the Windows guest VM and into VirtualBox's actual toolbars.

**Expected behavior**
Where the OS thinks the cursor is should be absolute upper-most corner e.g. pixel coordinates of x=1,y=1; for reference, this is how things work on Windows and, as mentioned, the issue does not occur within a Windows guest in a VM.

**Screenshots**
It is difficult to take actual screenshots of the issue, so I had to make due with manually creating simulated, zoomed-in images depicting what I see (the grey representing the bezel around the screen):

**Top-left**
![top_left](https://user-images.githubusercontent.com/11896003/179374225-50f68c30-16a7-4747-9953-b832ae82cbbc.png)

**Right side**
![right-side](https://user-images.githubusercontent.com/11896003/179374228-079ad2dd-c527-49a0-9ca7-52aa87182f0a.png)

**Bottom-right**
![bottom-right](https://user-images.githubusercontent.com/11896003/179374235-b24c9e12-1d41-4ed2-89ef-0d72b8843e26.png)

**Hardware*
This was tested on Thinkpad T420 (Sandy Bridge i5 + Intel integrated graphics) as well as a OneXPlayer "gaming" tablet (Ryzen 4800U + AMD integrated graphics), and this occured regardless of whether I used the internal display or an external monitor.

**Additional context**
As was mentioned at the beginning, the issue seem to also occur even in plain wayland on live Fedora 36 so I would think that one can at least rule out that xorg is at fault.

**Comment by JosephMcc** [comment]
Interesting. I have no idea what causes this. It could just be a matter of difference in coordinates or something. Is the first visible pixel considered 0,0 or 1,1 on different OS's. I am closing this however. It's not a beta issue. Or even an issue with any of our DE's or Mint in general.

**Comment by NintendoManiac64** [comment]
Well if it's not the fault of Mint, where should I go with reporting it?

**Comment by JosephMcc** [comment]
I have no idea. But considering it also happens under Fedora and Wayland it's obviously not a Mint issue or anything we have control over. I don't know if it's even a bug or just how it works under Linux. Which I suspect since it's also this way under Wayland. "Not like Windows" doesn't make it a bug.

**Comment by NintendoManiac64** [comment]
Saying "Not like Windows" was just an easier way to compare since, on the Linux side, it actually seems to be so prevalent and long-standing that you have to literally (not figuratively) go back a decade to the likes of Ubuntu 10.04 to find cases where it's not present (I have Mint 18.3 installed on an old PC connected to an HDTV repurposed as a monitor and the issue seems to occur there as well, but is mitigated by the fact that I'm using DPI scaling so I didn't really notice it).

From some quick testing I did just now, it seems that the vertical pixel offset "issue" exists even back in the original Ubuntu 4.10 which makes me think that specific aspect is indeed intentional, which honestly isn't that big of a deal to me as it is much less noticeable or annoying in day-to-day use.

Conversely, the horizontal pixel offset issue did not get introduced in Ubuntu until version 11.04, so version 10.10 was the last version of Ubuntu where the horizontal pixel offset issue did not occur.  So compared to the vertical pixel offset "issue", the horizontal pixel offset issue seems much more likely to be an actual bug and, of the two, the horizontal pixel offset is the one particularly bothers me as it prevents one from "hiding" the cursor via the right edge of the screen when using DMZ White (that is, with the horizontal pixel offset issue, both DMZ White and DMZ Black show a vertical white line where your cursor is or, if it's in the bottom-right corner, a bright white pixel - something that sticks out on dark themes in the middle of the night).

For reference, it was the mid to late 2000s when I last did a lot with Linux and I never noticed this being an issue at the time (which makes sense since it's the horizontal pixel offset that I really notice and that didn't exist at the time), and it wasn't until this year that I've really gotten back into Linux, so I never noticed when this issue first appeared.

**Comment by NintendoManiac64** [comment]
Doesn't the "Not a bug" label only applies to the vertical alignment portion, not the horizontal alignment?

I'll be honest, if the horizontal alignment is considered "intentional" then I can only see such intentional design change from Ubuntu 10.10 to 11.04 as being in the same vein as Gnome3 or Snap in being design choices that are simply considered undesirable compared to what came before it.

Nevertheless, I fully understand this being outside of the scope of the Mint 21 beta - I honestly just kind of can't believe the horizontal cursor alignment would be intentional as it just seems to be a downgrade in every way unless it was specifically meant to _prevent_ the cursor from being almost invisible when using DMZ White and putting the cursor on the far right... and it's actually the very ability to kind of "hide" the cursor on the right edge in this manner that I'm trying to "restore" if you will.
