### ISSUE TITLE
[Cinnamon - VM 1366x768 display] Push tile a large window fails as expected, but the window gets styled as a tile...

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/mint21-beta#83]
**Describe the bug**
I tried to push tile a window that was too large for a small screen, just to confirm it should not get tiled. That's okay. But the window gets styled as if it was tiled: it lost the rounded corners, shadows, and border on one side.

**To Reproduce**
1. Set display to 1366x768
2. Open Keyboard (`cinnamon-settings keyboard`)
3. Try to tile this window west or east, using the keyboard shortcuts
4. Box shadow, rounded corners, and one border, all disappeared

NOTE: It only happens sometimes...

**Expected behavior**
When tiling is not possible or not allowed, the window styling should remain unchanged.

**Screenshots**
![VirtualBox_LinuxMint-21-Cinnamon-BETA-false-tiling-on-1366x768](https://user-images.githubusercontent.com/31940713/179374665-8ab7493a-68d6-4baa-be1e-6e24e0778743.png)

**Hardware and mintUpdate**
* [inxi_-Fxxxrz.txt](https://github.com/linuxmint/mint21-beta/files/9126748/inxi_-Fxxxrz.txt)
* Is your system all up-to-date ? Yes.

**Additional context**
Started this story as an issue inside issue #77. Now moved into this new issue.

**Comment by JosephMcc** [comment]
I can reproduce this issue. The window thinks it's tiled. Grabbing the titlebar and dragging fixes it just like would happen with any tiled window.
