### ISSUE TITLE
Display Resolution incorrect at boot

### ISSUE THREAD

**Issue by pgmer6809** [linuxmint/mint21-beta#84]
Attempted to boot the Mint21 Cinnamon ISO from USB stick; Got a message on my display (from the display hardware I believe) telling me that the resolution was not correct and to set it to 1920x1080. The display works fine under Mint 20.3 Uma, although there are times when it will not wake up from suspend.
here is the inxi output
Graphics:
  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics 
  driver: i915 v: kernel 
  Device-2: NVIDIA GK208B [GeForce GT 710] driver: nvidia v: 470.129.06 
  Display: x11 server: X.Org 1.20.13 driver: modesetting,nvidia

**Comment by clefebvre** [comment]
So you're not able to boot? Do you see the boot sequence using compatibility mode?

**Comment by pgmer6809** [comment]
Hello.
Thanks for getting back to me.
1. I am sure this is a problem with X settings not with Vanessa itself.
2. On another computer, from the same USB,  I can boot fine, get to the
desktop etc.
This working computer has only Intel Integrated graphics with the i915
driver. Inxi -F shows 1280x1024 display on a VGA monitor.
3. The 'non working' computer has both an intel integrated graphics i915
driver AND an NVIDIA GT 710 Graphics card.
I am using the NVIDIA as the MOBO has not wired out the Intel GFX. The
Display in question is an HP 22FW.
When using UMA inxi -F shows this resolution as 1360x768~60Hz on a VGA
monitor.

The sequence is as follows.
1. UEFI -> Boot Menu -> Vanessa USB
2. Boot Vanessa -> Grub
3. Choose Normal (not compat mode) menu item
4. I get: a) the MINT logo, b) a brief view of systemd scrolling,  then a
black screen,  then a message that the Resolution is wrong and to adjust it.
(see screenshot below).
5. I then hear the sound that Mint makes when you do a successful login.
But the screen remains black.
6. If I do CTL-ALT-F1 I see a console display with some boot text msgs on
it.
7. If I do CTL-ALT-F2 I can get a terminal that I can login from.
8. INXI -F on this terminal shows the two Devices, i915 and NVIDIA. The
NVIDIA device is using the nouveau driver. The 'resolution' on the
terminal is 128 x 48.
9. If I run the top cmd (see screenshot below) I don't see any processes
that look like XWindow stuff.
10. If I run systemctl I see 209 out of 211 units, but again nothing that
looks to me like X11. The two units that are in RED are
casper-md5check.service and hddtemp.service. the setvtrgb.service is
running, if that is an X11 thing.
11. There are also some yellow units when I run systemctl --all but again
nothing that looks like X11.

If you think it would help I can hook up a different VGA monitor to this
computer to see if it works.
Or at the Grub menu I can try passing in some boot parameters; i've never
done that before so if you know which ones you want me to try just let me
know.

Regards,
Greg Morse
PS Thanks for a Wonderful Distro. Looking fwd to Vanessa.

**Comment by clefebvre** [comment]
Thanks Greg,

Ok, so it's definitely a rendering issue, not a kernel or a boot problem. I can't help unfortunately at this stage but I can suggest a few things to help troubleshoot the issue.

To troubleshoot this imo the best thing is to try different drivers and restart X11 to see if it helps.

From the console (ctrl-alt-f2) you can kill lightdm (`sudo kill -9 PID_OF_LIGHTDM` or `sudo killall lightdm`). This should either terminate the X11 or restart a new Lightdm, along with a new X11 instance. If it doesn't start a new one, you can either call lightdm as root (`sudo lightdm`) or call X11 directly (`startx`).

To check if you need drivers:  `sudo ubuntu-drivers list`

Also, before you try anything, do try the compatibility mode.

**Comment by pgmer6809** [comment]
Hi Clem,
FYI.
Booting in compat mode does not fix the problem.
sudo su then startx from a terminal (CTL-ALT-F2) has the same problem
(incorrect resolution) as the boot process.
but sudo lightdm WORKS.
I get a desktop (1280 x 768) and I can run Firefox, a virtual terminal, and
bring up the Mint Menu and go to Software sources etc.

Not sure what to make of all this; guess I wlll have to learn how to pass
parameters to the kernel from the grub menu.
But NP at this time.
Regards,
Greg
