### ISSUE TITLE
wrong dual monitor display positioning and no way to set permanently proper positioning

### ISSUE THREAD

**Issue by tethragon** [linuxmint/mint21-beta#85]
I open display utility and set my primary monitor as center monitor and I also set my secondary monitor on the LEFT of my primary monitor. Apply settings and it works. Fine.

Now, if I disable my second monitor and then I enable it again, then it defaults on the right, NOT REMEMBERING my previous settings. This is a problem inherited from Mint Cinnamon 20. Also every time I boot, during login my secondary monitor starts on the RIGHT, AGAIN not remembering my settings in Display utility.

Somehow my monitor positioning is not stored when I set it in Display utility. I think this issue should be fixed, since there are a lot of people with dual (or more) monitor setups.

**Comment by Cobinja** [comment]
The monitor position during login is because the settings done via cinnamon-settings are for your user profile only, not system-wide. For system-wide config, one possibility is to create /etc/X11/xorg.conf and let it resemble your profile's settings. If you use the proprietary nvidia drivers you can create such a file in nvidia-settings -> "X Server Display Configuration"

**Comment by tethragon** [comment]
> 

OK. 
In my humble opinion:

1) Display utility (I think it is xrandr) should give option to apply system-wide
2) Even user profile's settings are NOT stored properly, since when I disable and re-enable my second monitor, within the same session, it is positioned on the wrong side (right) and NOT on the side I had previously set (left). So there must be a bug there.

This is a problem that all Mint users with more than one monitor are having, for many years now. Maybe some are lucky and have their secondary monitor on the right (which is the system default) therefore this bug does not affect them. But anyone has a second monitor in any other position than right, must all the time change settings in the Display utility.

**Comment by clefebvre** [comment]
This isn't a regression so it's outside of the scope of this BETA.

1 isn't fixable easily.
2 isn't necessarily a bug. It depends what you mean by disabling the monitor. 

When you disable a monitor using the settings tool you effectively change the configuration of the set of these two monitors, you don't create a configuration with only one monitor. i.e. it's not the same scenario than when a monitor is unplugged. You specifically ask Cinnamon to remember to have this monitor disabled when it's plugged. In that scenario, it has no position.

If I'm mistaken please open a bug report on cinnamon directly at github.com/linuxmint/cinnamon/issues.
