### ISSUE TITLE
[Cinnamon] Systemmonitor - rounded corners

### ISSUE THREAD

**Issue by WebHeer** [linuxmint/mint21-beta#86]
The systemmonitor also has rounded corners at the bottom, unlike other windows.

**Comment by Acheron17** [comment]
Just to mention there are some other applications that share this feature, calculator, calendar, disks, fonts, logs, screenshot.

**Comment by WebHeer** [comment]
@Harry-W-Haines-III  - agree, but that's inconsistent in my opinion.

**Comment by JosephMcc** [comment]
The applications you are seeing that have rounded corners on the bottom are built with a library called libhandy. It's what causes the rounded corners on the bottom. I tried removing those in our themes but got some weird results when only trying to round the top corners and not the bottom. I can investigate further but I could only get it to work either having all rounded corners or none.

**Comment by mtwebster** [comment]
There's not really anything we can do here. Apparently it's not something that's themed, or at least something we can change in the theme.
