### ISSUE TITLE
Xapp: icon chooser hangs when selecting a path

### ISSUE THREAD

**Issue by startfree0** [linuxmint/mint21-beta#9]
When entering a new System Menu item, you are allowed to select an icon.  This can be one of many icons already in the build or a user defined icon.  In previous versions of Linux Mint this worked fine,  In LM 21 you can use the internal icons but NOT a user defined icon.  If you attempt to use a user defined icon the dialog box shows a spinning "Loading..." symbol which never stops.  This prevents the external icon from being used.

**Comment by SebastJava** [comment]
@startfree0 Could you list the precise **steps to reproduce** please ? Example:
1. Open menu > category > item
1. Click this button
1. Browse to image
1. Etc.

**Comment by startfree0** [comment]
Get to the "Menu Edit" dialog of the System Menu,  I have a new item already added.  Click on item, then click on "Properties".  This brings up the "Launcher Properties" dialog box. Click on icon. This brings up "Choose an icon" dialog box.  Don't select an icon but rather click "Browse" and navigate to a directory where your user provided icon resides.  In this case I select the Pale Moon icon in the package downloaded. Click on Open. Goes back to "Choose an icon" dialog where you see an empty dialog box and a spinning "Loading..." text in the corner. Normally the user defined icon would show up as an item in the dialog, where you would double click it to select and the icon would appear in the items "Launcher Properties"  Not in LM21 however.

**Comment by SebastJava** [comment]
That's okay. Don't worry. Just my own preferences as a designer... I will follow your instructions as you typed it. I am not ready yet, still installing...

**Comment by spamegg1** [comment]
I have the same issue.

**Comment by SebastJava** [comment]
ALL CONFIRMED on VirtualBox > Cinnamon install > mintUpdate all up-to-date > Guest additions installed > restarted

**Comment by spamegg1** [comment]
I can confirm it's fixed in Cinnamon 5.4.4.
