### ISSUE TITLE
Feature request (all versions): Wireshark and netcat on live media

### ISSUE THREAD

**Issue by ngaro** [linuxmint/mint21-beta#90]
Would it possible to include `wireshark` and `netcat` on the live isos ?

Reason:
* You (usually) need a network connection to install
* Sometimes you don't have enough information about the network to connect
* These 2 tools can provide __a lot__ of needed information

(For the same reason, but less important, `nmap` would also be nice)

**Comment by VaGNaroK** [comment]
> Would it possible to include `wireshark` and `netcat` on the live isos ?
> 
> Reason:
> 
> * You (usually) need a network connection to install
> * Sometimes you don't have enough information about the network to connect
> * These 2 tools can provide **a lot** of needed information
> 
> (For the same reason, but less important, `nmap` would also be nice)

Penetration testing distros already do this, although it is possible to install in live mode, having these tools is kind of illogical for a distro that intends to be "simple to use" like mint.

**Comment by ngaro** [comment]
The idea would be not to use it for pentesting but to configure the network if no dhcp is offered.

For example:
With `wireshark` you could examine the network and see dns requests from other machines so you would know which dns servers you should use.
You can also find out which router this other systems use and in which subnet they are located. Using this info you know which gateway to use. By combining this info with `ping` and/or `nmap` you have a reasonably idea what ip is still free to use and in which subnet it should be.

I have to admit you need some knowledge that is not trivial to use this, but including the packages is trivial (unless you also want to document it, but you could skip that).
The only disadvantage I see is that the iso is a couple of megabytes larger, but this is barely noticable.

**Comment by clefebvre** [comment]
netcat is already installed (via netcat-openbsd).
wireshark is a full QT UI app, it shouldn't be added.
