### ISSUE TITLE
[Xfce] Arrow in top-left of a program window does not 'unselect' if, on an unmaximized window, you click the arrow and select 'move' until you hover your cursor over it again or over the minimize, maximize, or close buttons

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/mint21-beta#96]
(tested in a live session of Xfce as well as a fully-updated local installation as of 2022-07-15)

**Describe the bug**
The arrow in top-left of any program window does not 'unselect' if, on an unmaximized window, you click the aforementioned arrow and select 'move' until you hover your cursor over it again or over the minimize, maximize, or close buttons

**To Reproduce**
1. boot into Mint 21 beta Xfce (whether a local installation or a live session)
2. open a program like Xed or Thunar
3. make sure that the current program window is not maximized
4. click the arrow in the top-left of the program window
5. click "Move"
6. left-click to stop the "Move" action
7. notice how the arrow in the top-left of the program window still looks like it is selected
8. hover your cursor over either the arrow again or over the minimize, maximize, or close button
9. notice how the arrow in the top-left of the program window has now become deselected

**Expected behavior**
The arrow in the top-left of the program window should be deselected after finishing the "Move" action

**Comment by clefebvre** [comment]
Nice catch. This is upstream from us though. The bug is in xfwm4 (part of the Xfce project) and should be reported there: https://gitlab.xfce.org/xfce/xfwm4/-/issues
