### ISSUE TITLE
blueman: Failed to apply network settings

### ISSUE THREAD

**Issue by VaGNaroK** [linuxmint/mint21-beta#98]
**Describe the bug**
when using the system normally, after restarting i came across these errors.

**To Reproduce**
I don't know how to reproduce since I don't use bluetooth on my pc and this message appeared out of nowhere.

**Expected behavior**
error?

**Screenshots**
https://postimg.cc/gallery/mCmxZfd

**Hardware and mintUpdate**
System:
  Kernel: 5.15.0-41-generic x86_64 bits: 64 compiler: gcc v: 11.2.0
    Desktop: Cinnamon 5.4.4 tk: GTK 3.24.33 vt: 7 dm: LightDM 1.30.0
    Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop Mobo: INTEL model: X79 v: V2.72B serial: <superuser required>
    UEFI: American Megatrends v: 4.6.5 date: 01/15/2021
CPU:
  Info: 6-core model: Intel Xeon E5-2620 0 bits: 64 type: MT MCP smt: enabled
    arch: Sandy Bridge rev: 7 cache: L1: 384 KiB L2: 1.5 MiB L3: 15 MiB
  Speed (MHz): avg: 1224 high: 1350 min/max: 1200/2500 cores: 1: 1200
    2: 1247 3: 1200 4: 1200 5: 1200 6: 1200 7: 1200 8: 1200 9: 1280 10: 1350
    11: 1221 12: 1200 bogomips: 48001
  Flags: avx ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: NVIDIA GK107 [GeForce GTX 650] driver: nvidia v: 470.129.06 pcie:
    speed: 2.5 GT/s lanes: 8 bus-ID: 03:00.0 chip-ID: 10de:0fc6 class-ID: 0300
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: nvidia
    gpu: nvidia display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1368x768 s-dpi: 96 s-size: 362x203mm (14.3x8.0")
    s-diag: 415mm (16.3")
  Monitor-1: DVI-I-0 res: 1368x768 hz: 60 size: N/A
  OpenGL: renderer: NVIDIA GeForce GTX 650/PCIe/SSE2
    v: 4.6.0 NVIDIA 470.129.06 direct render: Yes
Audio:
  Device-1: NVIDIA GK107 HDMI Audio driver: snd_hda_intel v: kernel pcie:
    speed: 5 GT/s lanes: 8 bus-ID: 03:00.1 chip-ID: 10de:0e1b class-ID: 0403
  Device-2: Generalplus USB Audio Device type: USB
    driver: hid-generic,snd-usb-audio,usbhid bus-ID: 1-1.2:3 chip-ID: 1b3f:2008
    class-ID: 0300
  Device-3: JMTek LLC. USB PnP Audio Device type: USB
    driver: hid-generic,snd-usb-audio,usbhid bus-ID: 1-1.5:4 chip-ID: 0c76:161f
    class-ID: 0300
  Sound Server-1: ALSA v: k5.15.0-41-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet
    driver: r8169 v: kernel pcie: speed: 2.5 GT/s lanes: 1 port: d000
    bus-ID: 07:00.0 chip-ID: 10ec:8168 class-ID: 0200
  IF: enp7s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
  Device-2: Microsoft Xbox 360 Wireless Adapter type: USB driver: xpad
    bus-ID: 2-1.5:4 chip-ID: 045e:0719 class-ID: ff00 serial: <filter>
Drives:
  Local Storage: total: 2.49 TiB used: 30.1 GiB (1.2%)
  ID-1: /dev/sda vendor: Crucial model: CT240BX500SSD1 size: 223.57 GiB
    speed: 6.0 Gb/s type: SSD serial: <filter> rev: R013 scheme: MBR
  ID-2: /dev/sdb vendor: Samsung model: HD204UI size: 1.82 TiB
    speed: 3.0 Gb/s type: HDD rpm: 5400 serial: <filter> rev: 0001 scheme: MBR
  ID-3: /dev/sdc vendor: Seagate model: ST500DM002-1BD142 size: 465.76 GiB
    speed: 3.0 Gb/s type: HDD rpm: 7200 serial: <filter> rev: KC45 scheme: GPT
Partition:
  ID-1: / size: 457.34 GiB used: 30.1 GiB (6.6%) fs: ext4 dev: /dev/sdc1
  ID-2: /boot/efi size: 41.3 MiB used: 5.2 MiB (12.6%) fs: vfat
    dev: /dev/sdc2
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 0 KiB (0.0%) priority: -2
    file: /swapfile
Sensors:
  System Temperatures: cpu: 34.0 C mobo: N/A gpu: nvidia temp: 36 C
  Fan Speeds (RPM): N/A gpu: nvidia fan: 16%
Repos:
  Packages: 2212 apt: 2195 flatpak: 17
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http://repositorio.nti.ufal.br/mint vanessa main upstream import backport
    2: deb http://sft.if.usp.br/ubuntu jammy main restricted universe multiverse
    3: deb http://sft.if.usp.br/ubuntu jammy-updates main restricted universe multiverse
    4: deb http://sft.if.usp.br/ubuntu jammy-backports main restricted universe multiverse
    5: deb http://security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/vivaldi.list
    1: deb [arch=amd64] https://repo.vivaldi.com/stable/deb/ stable main
  Active apt repos in: /etc/apt/sources.list.d/winehq-jammy.sources
    1: deb [arch=amd64 i386] https://dl.winehq.org/wine-builds/ubuntu jammy main
Info:
  Processes: 298 Uptime: 14m wakeups: 810 Memory: 19.48 GiB
  used: 1.81 GiB (9.3%) Init: systemd v: 249 runlevel: 5 Compilers:
  gcc: 11.2.0 alt: 11 Shell: Bash v: 5.1.16 running-in: gnome-terminal
  inxi: 3.3.13

the system is up to date as of the date of this report.

**Comment by clefebvre** [comment]
![image](https://user-images.githubusercontent.com/1138515/179910931-8ecad998-43a5-45fa-a97a-613fb3dc4e07.png)

**Comment by clefebvre** [comment]
This is known upstream as https://github.com/blueman-project/blueman/issues/1759.

**Comment by clefebvre** [comment]
@VaGNaroK can you kill all blueman* processes and run this to get a full output?

`blueman-applet --loglevel debug`

**Comment by clefebvre** [comment]
@VaGNaroK can you provide the output of this command also?

`journalctl -u blueman-mechanism.service`

**Comment by VaGNaroK** [comment]
> @VaGNaroK can you provide the output of this command also?
> 
> `journalctl -u blueman-mechanism.service`

https://gist.github.com/VaGNaroK/e6f3847c8456fcf4c662a61be327d0c6

I added a bluetooth on the pc to do tests, and it can pair with my xiaomi and receive a photo to the pc, at first everything is working fine, I don't know why that message that appeared last time.

**Comment by clefebvre** [comment]
This is tracked upstream.

On our side we'll update Blueman to 2.3.1 right now and then keep up with the updates post-release.
